package com.dj.hotelApi;

import java.util.List;

import com.dj.hotelApi.po.ModelData;
import com.dj.seal.hotel.po.Masterplatejudgep;
import com.dj.seal.modelFile.vo.ModelFileVo;
import com.dj.seal.modelFile.vo.ModelXieyiVo;

public class CopyOfPrintHtmlCode {
	private static String modelfolder="modelfolder";
//联通
	public static String getAllCode(List<ModelFileVo> masterplates,List<Masterplatejudgep> masterplateJudges,List<ModelXieyiVo> modelXieyis){
		StringBuffer sb = new StringBuffer();
		sb.append("<html>\r\n<head>\r\n<META HTTP-EQUIV=\"content-type\" CONTENT=\"text/html; charset=gb2312\">\r\n");
		sb.append(getStyleStr());
		sb.append("<title>打印页面</title>\r\n");
		sb.append(getScriptStr());
		sb.append("</head>\r\n");
		sb.append(getBodyStr(masterplates,masterplateJudges, modelXieyis));
		sb.append("</html>");
		return sb.toString();
	}
	
	
	public static String getStyleStr(){
		StringBuffer sb = new StringBuffer();
		sb.append(" 	<style>\r\n");
		sb.append("    .btn{ \r\n");
		sb.append("    BORDER-RIGHT: #7b9ebd 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7b9ebd 1px solid; PADDING-LEFT: 2px; FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#ffffff, EndColorStr=#cecfde); BORDER-LEFT: #7b9ebd 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #7b9ebd 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseout{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #9f9fa0 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #9f9fa0 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#f3f3f3, EndColorStr=#d9d9d9); BORDER-LEFT: #9f9fa0 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #9f9fa0 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseover{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #7EBF4F 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7EBF4F 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#8dda00, EndColorStr=#639800); BORDER-LEFT: #7EBF4F 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #7EBF4F 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mousedown \r\n");
		sb.append("    { \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #FFE400 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #FFE400 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#CC3300, EndColorStr=#CC3300); BORDER-LEFT: #FFE400 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #FFE400 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseup{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #7EBF4F 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7EBF4F 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#8dda00, EndColorStr=#639800); BORDER-LEFT: #7EBF4F 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #7EBF4F 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("     \r\n");
		sb.append("         a:link{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #FFFFFF;color: black; text-decoration: none; } \r\n");
		sb.append(" 		a:visited{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #FFFFFF; color: #639800; text-decoration: none;} \r\n");
		sb.append(" 		a:hover{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #639800; color: white; text-decoration: none;} \r\n");
		sb.append(" 		a:active{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #639800; color: white; text-decoration: none;} \r\n");
		sb.append("     \r\n");
		sb.append(" 		body{ \r\n");
		sb.append(" 			margin:0px; \r\n");
		sb.append(" 			font-family:\"微软雅黑\",\"雅黑\"; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 			background-color:\"#FDF5E6\"; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		span{ \r\n");
		sb.append(" 			width:40%; \r\n");
		sb.append(" 			text-align=\"right\"; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#TemplateDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			display:none; \r\n");
		sb.append(" 			border-style:solid;  \r\n");
		sb.append(" 			border-width:1px; \r\n");
		sb.append(" 			border-color: blue \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#TemplateTable{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			border-style:solid;  \r\n");
		sb.append(" 			border-width:1px; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#outerDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#headerDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:30px; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#menuBarAIP{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:10%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#mainDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:90%; \r\n");
		sb.append(" 			margin:10px,0,0,0; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#aipDiv{ \r\n");
		sb.append("				height:90%; \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			border-width:3px; \r\n");
		sb.append(" 			border-color:\"#FFA500\";  \r\n");
		sb.append(" 			border-style:solid; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		.ModalDialog {border: 1px #9F9F9F solid; background: #FFF; padding: 0px;margin: 10px auto; clear: both; position: absolute;  z-index: 10000;display:none;}\r\n");
		sb.append(" 		.header {border-bottom: 1px #DCDCDC solid; font-size: 12px; overflow: hidden; font-weight: normal; background: url('list_hd_bg.png') top left repeat-x;height:24px;}\r\n");
		sb.append(" 		.header .title {padding: 2px 3px;  float: left; font-weight: bold;line-height:20px;}\r\n");
		sb.append(" 		.header .operation {padding-top: 8px;padding-right:5px; float: right; cursor: pointer; text-decoration: none;}\r\n");
		sb.append(" 		.body {font-size: 9pt;margin: 0 !important; overflow-y: auto; padding: 10px 5px;}\r\n");
		sb.append(" 		.footer {padding: 0; text-align: center; font-size: 12px; margin-bottom: 10px;}\r\n");
		sb.append(" 	</style>\r\n");
		return sb.toString();
	}
	
	public static String getScriptStr(){
		StringBuffer sb = new StringBuffer();
		sb.append(" 	<script>\r\n");
		sb.append("    		var isSetXieyi=false; \r\n");
		sb.append(" 		var currZancunFile=-1;\r\n");
		sb.append(" 		var username=\"guest\";\r\n");
		sb.append(" 		var modelfolder=\""+modelfolder+"\";\r\n ");
		sb.append(" 		var userStatus=0;\r\n");
		sb.append(" 		var savePath=\"d:/hoteltest/guest\";\r\n");
		sb.append(" 		var currtemplateName=\"\";\r\n");
		sb.append(" 		var currdispayName=\"\";\r\n");
		sb.append(" 		var currtemplateIsTaoDa=0;\r\n");
		sb.append(" 		var openZancun=0;\r\n");
		sb.append(" 		var ocxReady=0;\r\n");
		sb.append(" 		var printFilePath;\r\n");
		sb.append(" 		var isFind=0;\r\n");
		sb.append(" 		var huodongyepage=0;\r\n");
		sb.append(" 		function onLoad(){\r\n");
		sb.append(" 			var tempInfo=document.getElementById(\"templateInfo\").value;\r\n");
		sb.append(" 			var temparr=eval(tempInfo);\r\n");
		sb.append(" 			getParamFromURL();\r\n");
		sb.append(" 			ocxReady=ocxReady+1;\r\n");
		sb.append(" 			if(ocxReady==2){	\r\n");
		sb.append(" 				comparisonTemplate();\r\n");
		sb.append(" 				setTemplateTable();\r\n");
		sb.append(" 			}			\r\n");
		sb.append(" 		}\r\n");
		sb.append(" 		function getParamFromURL(){\r\n");
		sb.append(" 			var url=window.location.href;\r\n");
		sb.append(" 			var temp=url.split(\"?\");\r\n");
		sb.append(" 			var params=temp[1].split(\"&\");\r\n");
		sb.append(" 			username=params[0].split(\"=\")[1];\r\n");
		sb.append(" 			userStatus=params[1].split(\"=\")[1];\r\n");
		sb.append(" 			savePath=params[2].split(\"=\")[1];\r\n");
		sb.append(" 			savePath=savePath.replace(/%20/g, \" \");\r\n ");
		sb.append(" 			printFilePath=params[3].split(\"=\")[1];\r\n");
		sb.append(" 			printFilePath=printFilePath.replace(/%20/g, \" \");\r\n ");
		sb.append(" 		}\r\n");
		sb.append(" 		function setTemplateTable(){\r\n");
		sb.append(" 			var tempInfo=document.getElementById(\"templateInfo\").value;\r\n");
		sb.append(" 			var temparr=eval(tempInfo);\r\n");
		sb.append(" 			var tempDiv=document.getElementById(\"TemplateDiv\");\r\n");
		sb.append(" 			var s=\"\";\r\n");
		sb.append(" 			for(var i=0;i<temparr.length;i++){\r\n");
		sb.append(" 				s=s+'<div id=\"tempDiv_child\"+i style=\"margin-left:5px;float:left;\">'\r\n");
		sb.append(" 				s=s+'<div style=\"background-image:url(images/top_2_03.gif);width:37px;height:37px;float:left;\"></div>'\r\n");
		sb.append(" 				s=s+'<div onclick=useTempplate(\"'+temparr[i].name+'\",\"'+temparr[i].display+'\") style=\"background-image:url(images/top_2_05.gif);height:37px;float:left;padding:9px;width:200px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;\">'\r\n");
		sb.append(" 				s=s+'<font style=\"font-size:18px;font-family:华文行楷;\">'+temparr[i].display+'</font>'\r\n");
		sb.append(" 				s=s+'</div>'\r\n");
		sb.append(" 				s=s+'</div>'\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 			tempDiv.innerHTML=s;\r\n");
		sb.append(" 		}\r\n");
		sb.append(" 		var isshowTemplateDiv=0;\r\n");
		sb.append(" 		function showTemplateDiv(){\r\n");
		sb.append(" 			if(isshowTemplateDiv==0){\r\n");
		sb.append(" 				document.getElementById(\"TemplateDiv\").style.display=\"block\";\r\n");
		//sb.append(" 				document.getElementById(\"TemplateButton\").value=\"隐藏模板\";\r\n");
		sb.append(" 				document.getElementById(\"TemplateButton\").src=\"images/002.gif\";\r\n");
		sb.append(" 				isshowTemplateDiv=1;\r\n");
		sb.append(" 			}else{\r\n");
		sb.append(" 				document.getElementById(\"TemplateDiv\").style.display=\"none\";\r\n");
		//sb.append(" 				document.getElementById(\"TemplateButton\").value=\"显示模板\";\r\n");
		sb.append(" 				document.getElementById(\"TemplateButton\").src=\"images/001.gif\";\r\n");
		sb.append(" 				isshowTemplateDiv=0;\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 		}\r\n");
		sb.append(" 		function useTempplate(templateName,templateDisplay){\r\n");
		sb.append(" 			currtemplateName=templateName;\r\n");
		sb.append(" 			currdispayName=templateDisplay;\r\n");
		sb.append("    			isSetXieyi=false; \r\n");
		sb.append(" 			var temp=document.getElementById(currtemplateName+\"Data\").value;\r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
		sb.append(" 			objAIP.CloseDoc(0);\r\n");
		sb.append(" 			objAIP.LoadFile(printFilePath);\r\n");
		sb.append(" 			objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\");\r\n");
		sb.append(" 			objAIP.SetValue(\"PASTE_NODES_FROMDATA\",temp);\r\n");
		sb.append(" 			objAIP.Logout();\r\n");
		sb.append(" 			var istaoda=document.getElementById(currtemplateName+\"TaoDa\").value;\r\n");
		sb.append(" 			if(istaoda==\"1\"){\r\n");
		sb.append(" 						if(currdispayName==\"业务变更单\"){ \r\n ");
		sb.append(" 							  var kongbaitemplate=document.getElementById(\"空白页\");    \r\n ");
		sb.append("				   			var data = kongbaitemplate.value;    \r\n ");
		sb.append("				   			var pagenum = objAIP.PageCount;    \r\n ");
		sb.append("				   			objAIP.Login(username,2, 65535,\"\",\"\");    \r\n ");
		sb.append("				   			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);   \r\n ");
		sb.append("				   			objAIP.Logout();     \r\n ");
		sb.append(" 						} \r\n ");
		//sb.append(" 						var templateBase64=document.getElementById(currtemplateName).value;\r\n");
		//sb.append(" 						objAIP.SetBackgroundDoc(\"STRDATA:\"+templateBase64,\"\",0);\r\n");
		sb.append(" 						objAIP.SetBackgroundDoc(savePath+\"/\"+modelfolder+\"/\"+templateName,\"\",0);\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 			document.getElementById(\"message\").innerText=\"当前使用模板：\"+currdispayName;\r\n");
		
//		sb.append(" 				if(currdispayName==\"临时住宿登记表\"){ \r\n ");
//		sb.append(" 					var tableTemplateBase64=document.getElementById(\"红色表格页\").value; \r\n ");
//		sb.append(" 					objAIP.SetBackgroundDoc(\"STRDATA:\"+tableTemplateBase64,\"\",0); \r\n ");
//		sb.append(" 				}  \r\n ");
		
		sb.append(" 				if(currdispayName==\"业务变更单\"){ \r\n ");
		sb.append(" 					var positionInfo = objAIP.FindText(\"客户签字\",0,0,0,0,0,50000,50000,1);//查找文字、是否区分大小写、开始页、开始横坐标、开始纵坐标、结束页、结束横坐标、结束纵坐标、查找第几处 \r\n ");
		sb.append(" 					if(positionInfo!=null&&positionInfo!=\"\"){ \r\n ");
		sb.append(" 						var pps = positionInfo.split(\",\"); \r\n ");
		sb.append(" 						if(pps.length==3){ \r\n ");
		sb.append(" 							var textpage = pps[0]; \r\n ");
		sb.append("	 							var heng = parseInt(pps[1])+8000; \r\n ");
		sb.append("	 							var zong = parseInt(pps[2])-200; \r\n ");
		sb.append("	 							objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\"); \r\n ");
		sb.append("	 							objAIP.InsertNote(\"PredefineSignArea\",textpage,2,heng,zong,6000,1000); \r\n ");
		sb.append("	 							objAIP.SetValue(\"Page\"+(parseInt(textpage)+1)+\".PredefineSignArea\",\":PROP:BORDER:0\"); \r\n ");
		sb.append("	 							objAIP.Logout(); \r\n ");
		sb.append(" 						} \r\n ");
		sb.append(" 					} \r\n ");
		sb.append("  				}else if(currdispayName==\"入网登记单\"){ \r\n ");
		sb.append("   								var positionInfo = objAIP.FindText(\"客户签字\",0,0,0,0,0,50000,50000,1);//查找文字、是否区分大小写、开始页、开始横坐标、开始纵坐标、结束页、结束横坐标、结束纵坐标、查找第几处 \r\n ");
		sb.append("				  					objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\"); \r\n ");
		sb.append("				  					if(positionInfo!=null&&positionInfo!=\"\"){\r\n ");
		sb.append("				  						var pps = positionInfo.split(\",\"); \r\n ");
		sb.append("				  						if(pps.length==3){\r\n ");
		sb.append("				  							var textpage = pps[0]; \r\n ");
		sb.append("				 	 							var heng = parseInt(pps[1])+8500; \r\n ");
		sb.append("				 	 							var zong = parseInt(pps[2])-200; \r\n ");
		sb.append("				 	 							objAIP.InsertNote(\"PredefineSignArea\",textpage,2,heng,zong,6000,1300); \r\n ");
		sb.append("				 	 							objAIP.SetValue(\"Page\"+(parseInt(textpage)+1)+\".PredefineSignArea\",\":PROP:BORDER:0\"); \r\n ");
		sb.append("				  						} \r\n ");
		sb.append("				  					} \r\n ");
//		sb.append("				  					objAIP.InsertNote(\"SignAreaDef\",1,2,3000,1900,6000,1300);  \r\n ");
//		sb.append("  	 								objAIP.SetValue(\"Page2.SignAreaDef\",\":PROP:BORDER:0\");  \r\n ");
//		sb.append("	 	 								objAIP.SetValue(\"Page2.SignAreaDef\",\":PROP:FORCEIN:1\");\r\n ");
		sb.append("				  					objAIP.Logout();\r\n ");
		sb.append("  				}   \r\n ");
		sb.append("				var myDate = new Date();\r\n ");
		sb.append("				var code=\"\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+parseInt(100*Math.random());\r\n ");
		sb.append("				objAIP.SetValue(\"code\",\"\");\r\n ");
		sb.append("				objAIP.SetValue(\"code\",code);\r\n ");
		sb.append(" 		}		\r\n");
		sb.append(" 		function comparisonTemplate(){\r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
		sb.append(" 			var tempInfo=document.getElementById(\"templateInfo\").value;\r\n");
		sb.append(" 			var temparr=eval(tempInfo);\r\n");
		sb.append(" 			for(var i=0;i<temparr.length;i++){\r\n");
		sb.append(" 				var compareValue=document.getElementById(temparr[i].name+\"Comparison\").value;\r\n");
		sb.append(" 				var comparearr=eval(compareValue);\r\n");
		sb.append(" 				var temp=document.getElementById(temparr[i].name+\"Data\").value;\r\n");
		sb.append(" 				objAIP.CloseDoc(0);\r\n");
		sb.append(" 				objAIP.LoadFile(printFilePath);\r\n");
		sb.append(" 				objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\");\r\n");
		sb.append(" 				objAIP.SetValue(\"PASTE_NODES_FROMDATA\",temp);\r\n");
		sb.append(" 				objAIP.Logout();\r\n");
		sb.append(" 				for(var j=0;j<comparearr.length;j++){\r\n");
		sb.append(" 					isFind=1;\r\n");
		sb.append(" 					var name=comparearr[j].name;\r\n");
		sb.append(" 					var comValue=comparearr[j].display;\r\n");
		sb.append(" 					var TemplateValue=objAIP.GetValueEx(name,42,\"\",0,\"\");\r\n");
		sb.append(" 					if(comValue==\"DJ_UNEMPTY_VALUE\"){\r\n");
		sb.append(" 						if(TemplateValue==\"\"){isFind=0;break;}\r\n");
		sb.append(" 					}else if(comValue==\"DJ_EMPTY_VALUE\"){\r\n");
		sb.append(" 						if(TemplateValue!=\"\"){isFind=0;break;}\r\n");
		sb.append("						}else if(comValue==\"DJ_FIND_TEXT\"){ \r\n ");
		sb.append(" 						var positionInfo = objAIP.FindText(name,0,0,0,0,0,50000,50000,1);//查找文字、是否区分大小写、开始页、开始横坐标、开始纵坐标、结束页、结束横坐标、结束纵坐标、查找第几处  \r\n ");
		sb.append("  						if(positionInfo==null||positionInfo==\"\"){ \r\n ");
		sb.append("  							isFind=0;break; \r\n ");
		sb.append("  						} \r\n ");
		sb.append(" 					}else{ \r\n ");
		sb.append(" 						if(TemplateValue.indexOf(comValue)==-1){isFind=0;break;}\r\n");
		sb.append(" 					}\r\n");
		sb.append(" 				}\r\n");
		sb.append(" 				if(isFind){\r\n");
		sb.append(" 					currtemplateName=temparr[i].name;\r\n");
		sb.append(" 					currdispayName=temparr[i].display;\r\n");
		sb.append(" 					var istaoda=document.getElementById(currtemplateName+\"TaoDa\").value;\r\n");
		sb.append(" 					if(istaoda==\"1\"){\r\n");
		sb.append(" 						if(currdispayName==\"业务变更单\"){ \r\n ");
		sb.append(" 							  var kongbaitemplate=document.getElementById(\"空白页\");    \r\n ");
		sb.append("				   				var data = kongbaitemplate.value;    \r\n ");
		sb.append("				   				var pagenum = objAIP.PageCount;    \r\n ");
		sb.append("				   				objAIP.Login(username,2, 65535,\"\",\"\");    \r\n ");
		sb.append("				   				var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);   \r\n ");
		sb.append("				   				objAIP.Logout();     \r\n ");
		sb.append(" 						} \r\n ");
		//sb.append(" 						var templateBase64=document.getElementById(currtemplateName).value;\r\n");
		//sb.append(" 						objAIP.SetBackgroundDoc(\"STRDATA:\"+templateBase64,\"\",0);\r\n");
		sb.append(" 						objAIP.SetBackgroundDoc(savePath+\"/\"+modelfolder+\"/\"+currtemplateName,\"\",0);\r\n");
		sb.append(" 						break;\r\n");
		sb.append(" 					}else{\r\n");
		sb.append(" 						break;\r\n");
		sb.append(" 					}\r\n");
		sb.append(" 				}\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 			if(!isFind){\r\n");
		sb.append(" 			    objAIP.CloseDoc(0);\r\n");
		sb.append(" 			    objAIP.LoadFile(printFilePath);\r\n");
		sb.append(" 				document.getElementById(\"message\").innerText=\"未自动匹配到模板，请手工选择\";\r\n");
		sb.append(" 			}else{\r\n");
		sb.append(" 				document.getElementById(\"message\").innerText=\"当前使用模板：\"+currdispayName;\r\n");
		
//		sb.append(" 				if(currdispayName==\"临时住宿登记表\"){ \r\n ");
//		sb.append(" 					var tableTemplateBase64=document.getElementById(\"红色表格页\").value; \r\n ");
//		sb.append(" 					objAIP.SetBackgroundDoc(\"STRDATA:\"+tableTemplateBase64,\"\",0); \r\n ");
//		sb.append(" 				}  \r\n ");
		sb.append(" 				if(currdispayName==\"业务变更单\"){ \r\n ");
		sb.append(" 					var positionInfo = objAIP.FindText(\"客户签字\",0,0,0,0,0,50000,50000,1);//查找文字、是否区分大小写、开始页、开始横坐标、开始纵坐标、结束页、结束横坐标、结束纵坐标、查找第几处 \r\n ");
		sb.append(" 					if(positionInfo!=null&&positionInfo!=\"\"){ \r\n ");
		sb.append(" 						var pps = positionInfo.split(\",\"); \r\n ");
		sb.append(" 						if(pps.length==3){ \r\n ");
		sb.append(" 							var textpage = pps[0]; \r\n ");
		sb.append("	 							var heng = parseInt(pps[1])+8000; \r\n ");
		sb.append("	 							var zong = parseInt(pps[2])-200; \r\n ");
		sb.append("	 							objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\"); \r\n ");
		sb.append("	 							objAIP.InsertNote(\"PredefineSignArea\",textpage,2,heng,zong,6000,1000); \r\n ");
		sb.append("	 							objAIP.SetValue(\"Page\"+(parseInt(textpage)+1)+\".PredefineSignArea\",\":PROP:BORDER:0\"); \r\n ");
		sb.append("	 							objAIP.Logout(); \r\n ");
		sb.append(" 						} \r\n ");
		sb.append(" 					} \r\n ");
		sb.append("  				}else if(currdispayName==\"入网登记单\"){ \r\n ");
		sb.append("   								var positionInfo = objAIP.FindText(\"客户签字\",0,0,0,0,0,50000,50000,1);//查找文字、是否区分大小写、开始页、开始横坐标、开始纵坐标、结束页、结束横坐标、结束纵坐标、查找第几处 \r\n ");
		sb.append("				  					objAIP.Login(\"sys_admin\",5, 65535, \"DEMO\", \"\"); \r\n ");
		sb.append("				  					if(positionInfo!=null&&positionInfo!=\"\"){\r\n ");
		sb.append("				  						var pps = positionInfo.split(\",\"); \r\n ");
		sb.append("				  						if(pps.length==3){\r\n ");
		sb.append("				  							var textpage = pps[0]; \r\n ");
		sb.append("				 	 							var heng = parseInt(pps[1])+8500; \r\n ");
		sb.append("				 	 							var zong = parseInt(pps[2])-200; \r\n ");
		sb.append("				 	 							objAIP.InsertNote(\"PredefineSignArea\",textpage,2,heng,zong,6000,1300); \r\n ");
		sb.append("				 	 							objAIP.SetValue(\"Page\"+(parseInt(textpage)+1)+\".PredefineSignArea\",\":PROP:BORDER:0\"); \r\n ");
		sb.append("				  						} \r\n ");
		sb.append("				  					} \r\n ");
//		sb.append("				  					objAIP.InsertNote(\"SignAreaDef\",1,2,3000,1900,6000,1300);  \r\n ");
//		sb.append("  	 								objAIP.SetValue(\"Page2.SignAreaDef\",\":PROP:BORDER:0\");  \r\n ");
//		sb.append("	 	 								objAIP.SetValue(\"Page2.SignAreaDef\",\":PROP:FORCEIN:1\");\r\n ");
		sb.append("				  					objAIP.Logout();\r\n ");
		sb.append("  				} else if(currdispayName==\"发票\"){   \r\n ");
		sb.append(" 					var pagenum = objAIP.PageCount;  \r\n");
		sb.append(" 					var printret = objAIP.PrintDocEx(\"Test-Printer\",1,0,1,1,pagenum,1,1,1,0,0);  \r\n");
		sb.append(" 					if(printret<=0){  \r\n");
		sb.append(" 						alert(\"打印失败,请将打印机名称设置为：Test-Printer\"); \r\n");
		sb.append(" 						return false; \r\n");
		sb.append(" 					} \r\n");
	    sb.append(" 					window.opener=null;\r\n");
	    sb.append(" 					window.open('', '_self', '');\r\n");
		sb.append(" 					window.close();\r\n");
		sb.append(" 				}  \r\n ");
		
		sb.append(" 			}\r\n");
		sb.append("				var myDate = new Date();\r\n ");
		sb.append("				var code=\"\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+parseInt(100*Math.random());\r\n ");
		sb.append("				objAIP.SetValue(\"code\",\"\");\r\n ");
		sb.append("				objAIP.SetValue(\"code\",code);\r\n ");
		sb.append(" 		}\r\n");
		sb.append(" 		function handWrite(){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			objAIP.Login(username,2, 65535,\"\",\"\");\r\n ");
		sb.append("  			objAIP.ShowFullScreen = 1;\r\n ");
		sb.append("  			objAIP.SetValue(\"ENABLE_COMMENT_MODE\", \"0\");//退出注释状态\r\n ");
		sb.append("  			objAIP.CurrAction=264;\r\n ");
		sb.append(" 		}\r\n ");
		
		sb.append(" 		function lookdanju(){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			objAIP.Login(username,2, 65535,\"\",\"\");\r\n ");
		sb.append("  			objAIP.ShowFullScreen = 1;\r\n ");
		sb.append(" 		}\r\n ");
		
		sb.append(" 		\r\n ");
		sb.append(" 		function biaozhu(){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 				objAIP.ShowFullScreen = 1;\r\n ");
		sb.append("  			objAIP.SetValue(\"ENABLE_COMMENT_MODE\", \"1\");//进入注释状态\r\n ");
		sb.append(" 		}\r\n ");
		
		sb.append("     var isnowhuodong = \"no\";   \r\n ");
		sb.append("     var yinhangpage;;   \r\n ");
		sb.append("      function addHuoDong(){    \r\n");
		sb.append("  					if(isnowhuodong==\"no\"){     \r\n");
		sb.append("  						var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append("				   			objAIP.Login(username,2, 65535,\"\",\"\");     \r\n");
		sb.append("  						var huodong=document.getElementById(\"协议页\");      						   \r\n");
		sb.append(" 				   			var data = huodong.value;     \r\n");
		sb.append(" 				   			var pagenum = objAIP.PageCount;     \r\n");
		sb.append(" 				   			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);    \r\n");
		sb.append("  						huodongyepage=pagenum; \r\n");
		sb.append("				   			objAIP.Logout();      \r\n");
		sb.append("      					isnowhuodong = \"yes\";    \r\n");
		sb.append("      					document.getElementById(\"huodong\").value=\"删除协议\";  \r\n");
		sb.append("  					}else{     \r\n");
		sb.append("  						if(window.confirm(\"确定要删除协议页?\")){ \r\n");
		sb.append(" 							var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append("				   			objAIP.Login(username,2, 65535,\"\",\"\");     \r\n");
		sb.append("  							objAIP.DeletePage(huodongyepage);  ; \r\n");
		sb.append("				   			objAIP.Logout();      \r\n");
		sb.append("      						isnowhuodong = \"no\"; \r\n");
		sb.append("      						zhengjianpage = zhengjianpage -1; \r\n");
		sb.append("      					document.getElementById(\"huodong\").value=\"添加协议\";  \r\n");
		sb.append("  						}     \r\n");
		sb.append("  					}     \r\n");
		sb.append("  		} \r\n");

		
		
		sb.append("   //加载核心 \r\n");
		sb.append("  function LoadRecogKenalDuKa() \r\n");
		sb.append("  { \r\n");
		sb.append("     if(!objIDCardDuKa.IsLoaded()){ \r\n");
		sb.append("         var nRet = objIDCardDuKa.Init(); \r\n");
		sb.append("         if(nRet==0x90){  \r\n");
		sb.append("     //       alert(\"二代证核心加载成功\"); \r\n");
		sb.append("         } \r\n");
		sb.append("         else{ \r\n");
		sb.append("           alert(\"二代证核心加载失败,返回值：\"+nRet); \r\n");
		sb.append("         } \r\n");
		sb.append("      }else{ \r\n");
		sb.append("            document.IDScanRecog.result.innerText = \"核心已经加载\"; \r\n");
		sb.append("      } \r\n");
		sb.append("    \r\n");
		sb.append("  } \r\n");
		sb.append("  //释放核心 \r\n");
		sb.append("  function FreeRecogKenalDuKa() \r\n");
		sb.append("  { \r\n");
		sb.append("      objIDCardDuKa.Free(); \r\n");
		sb.append("  } \r\n");
		sb.append("    		 \r\n");
		sb.append("    		 \r\n");
		sb.append("    		 \r\n");
		sb.append("    		//加载核心 \r\n ");
		sb.append("   function LoadRecogKenal() \r\n ");
		sb.append("   { \r\n ");
		sb.append("       if(!objIDCard.IsLoaded()) \r\n ");
		sb.append("       { \r\n ");
		sb.append("          var strDllPath = \"\"; \r\n ");
		sb.append("          var nRet = objIDCard.InitIDCard(\"66915733240632479518\",0); \r\n ");
		sb.append("          if(nRet==0) \r\n ");
		sb.append("          {  \r\n ");
		sb.append("   //          alert(\"识别核心加载成功\"); \r\n ");
		sb.append("   	  			nRet = objIDCard.SetSpecialAttribute(1,1); \r\n ");
		sb.append("            if(nRet==1) \r\n ");
		sb.append("           { \r\n ");
		sb.append("   	   		alert(\"设置特殊标志失败\"); \r\n ");
		sb.append("           } \r\n ");
		sb.append("          } \r\n ");
		sb.append("          else \r\n ");
		sb.append("          { \r\n ");
		sb.append("            alert(\"识别核心加载失败,返回值：\"+nRet); \r\n ");
		sb.append("            if(nRet==1) \r\n ");
		sb.append("            { \r\n ");
		sb.append("               alert(\"(无效的UserID)\"); \r\n ");
		sb.append("            } \r\n ");
		sb.append("          } \r\n ");
		sb.append("       } \r\n ");
		sb.append("   } \r\n ");
		sb.append("   //释放核心 \r\n ");
		sb.append("   function FreeRecogKenal() \r\n ");
		sb.append("   { \r\n ");
		sb.append("       objIDCard.FreeIdcard(); \r\n ");
		sb.append("   } \r\n ");
		sb.append("     		 \r\n ");
		sb.append("     var iszhengfan = \"zheng\";\r\n");
		sb.append("     \r\n");
		sb.append("         function addIdCardImg(){    \r\n");
		sb.append("       			var objAIP=document.getElementById(\"HWPostil1\");    \r\n");
		sb.append("       			var doctype = objAIP.CurrDocType;      \r\n");
		sb.append("       			if(doctype==31){    \r\n");
		sb.append("       				alert(\"文档已盖章，不能修改！\");    \r\n");
		sb.append("       				return false;    \r\n");
		sb.append("       			}    \r\n");
		sb.append("       			var vRet = objAIP.Login(username,2, 65535,\"\",\"\");    \r\n");
		sb.append("       			var idcardtemplate=document.getElementById(\"身份证图片页\");    \r\n");
		sb.append("       			var data = idcardtemplate.value;    \r\n");
		sb.append("       			var pagenum = objAIP.PageCount;    \r\n");
		sb.append("       			var m ;\r\n");
		sb.append("       			if(iszhengfan==\"zheng\"){\r\n");
		sb.append("       				var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);  \r\n");
		sb.append("       			}else{\r\n");
		sb.append("       				m=1;\r\n");
		sb.append("       			}\r\n");
		sb.append("       			if(m==1){\r\n");
		sb.append("         				pagenum = objAIP.PageCount;  \r\n");
		sb.append("         				var deletepagenum =  pagenum -1;   \r\n");
		sb.append("	       				var openret=CardReader_CMCC.MutiIdCardOpenDevice(1000);//打开设备    \r\n");
		sb.append("	     					if(openret!=0){    \r\n");
		sb.append("	     						LoadRecogKenal(); \r\n");
		sb.append("	     						if(objIDCard.IsLoaded()){ \r\n");
		sb.append("	    				        //采集图像 \r\n");
		sb.append("	    				        var nResult = objIDCard.AcquireImage(\"2\"); \r\n");
		sb.append("	    				        if(nResult!=0) { \r\n");
		sb.append("	    				           var strError = \"采集图像失败,返回值：\"; \r\n");
		sb.append("	    				           strError += nResult; \r\n");
		sb.append("	    				           alert(strError); \r\n");
		sb.append("	    				           return; \r\n");
		sb.append("	    				       } \r\n");
		sb.append("	    				       //调用识别接口识别 \r\n");
		sb.append("	    				       //设置要识别的证件类型 \r\n");
		sb.append("	    				       //0表示添加次主类型的所有子模板 \r\n");
		sb.append("	    				       objIDCard.SetIDCardType(\"2\",0);     				        \r\n");
		sb.append("	    				       //识别 \r\n");
		sb.append("	    				       nResult = objIDCard.RecogIDCard();  \r\n");
		sb.append("	    				        if(nResult<=0){ \r\n");
		sb.append("	    				           var strError = \"识别失败,返回值：\"; \r\n");
		sb.append("	    				           strError += nResult; \r\n");
		sb.append("	    				           alert(strError); \r\n");
		sb.append("	    				           return; \r\n");
		sb.append("	    				        }   \r\n");
		sb.append("	    				      //保存图像 \r\n");
		sb.append("	    				        objIDCard.SaveImage(\"c:/test.jpg\"); \r\n");
		sb.append("	    				        //保存头像 \r\n");
		sb.append("	    				         objIDCard.SaveHeadImage(\"c:/test_head.jpg\"); \r\n");
		sb.append("	    				         if(iszhengfan==\"zheng\"){\r\n");
		sb.append("		    				      		objAIP.SetValue(\"Page\"+pagenum+\".idcardpicture\",\"BMPFILE:c:/test.jpg\"); \r\n");
		sb.append("		    				      	}else{\r\n");
		sb.append("		    				      		objAIP.SetValue(\"Page\"+pagenum+\".idcardpicturefan\",\"BMPFILE:c:/test.jpg\"); \r\n");
		sb.append("		    				      	}  \r\n");
		sb.append("		        			     	objAIP.CurrPage(deletepagenum);//跳转到第二页  \r\n");
		sb.append("		        			     if(iszhengfan==\"zheng\"){\r\n");
		sb.append("		        			     			 //显示识别结果 \r\n");
		sb.append("						    				     var nFieldNum = objIDCard.GetRecogFieldNum(); \r\n");
		sb.append("						    				     var strResult = \"识别成功\";  \r\n");
		sb.append("						    				     if(nFieldNum>0) {   \r\n");
		sb.append("									    				   //       for(var i=1;i<=nFieldNum;++i)  \r\n");
		sb.append("									    				   //      { \r\n");
		sb.append("									    				   //          strResult += objIDCard.GetFieldName(i); \r\n");
		sb.append("									    				   //          strResult += \":\"; \r\n");
		sb.append("									    				   //          strResult += objIDCard.GetRecogResult(i); \r\n");
		sb.append("									    				   //          strResult += \"\"; \r\n");
		sb.append("									    				   var huoquGuestname = objIDCard.GetRecogResult(1); \r\n");
		sb.append("									    				    var huoquCardno = objIDCard.GetRecogResult(6); \r\n");
		sb.append("									    				    var danjuGuestname =objAIP.GetValueEx(\"guestname\",42,\"\",0,\"\"); \r\n");
		sb.append("									        				danjuGuestname = danjuGuestname.replace(/^\\s+|\\s+$/g,\"\"); \r\n");
		sb.append("									        				var danjuCardNo =objAIP.GetValueEx(\"cardNo\",42,\"\",0,\"\"); \r\n");
		sb.append("									        				danjuCardNo = danjuCardNo.replace(/^\\s+|\\s+$/g,\"\"); \r\n");
		sb.append("									         				if(huoquGuestname==\"\"||huoquCardno==\"\"){\r\n");
		sb.append("									        					    alert(\"未识别到身份证信息，请检查是否放入了身份证\"); \r\n");
		sb.append("											    		    			objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("											     						FreeRecogKenal(); \r\n");
		sb.append("											    		    			return false; \r\n");
		sb.append("									        				}\r\n");
		sb.append("									   		    		if(danjuGuestname.indexOf(huoquGuestname)==-1||danjuCardNo.indexOf(huoquCardno)==-1){ \r\n");
		sb.append("									    		    			alert(\"身份证信息与客户基本信息不一致，请检查\"); \r\n");
		sb.append("									    		    			objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("									     							FreeRecogKenal(); \r\n");
		sb.append("									    		    			return false; \r\n");
		sb.append("									    		    		}\r\n");
		sb.append("									    		    		iszhengfan=\"fan\";\r\n");
		sb.append("						    				     }else{ \r\n");
		sb.append("							    		    			alert(\"未识别到身份证信息，请检查是否放入了身份证\"); \r\n");
		sb.append("							    		    			objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("							     							FreeRecogKenal(); \r\n");
		sb.append("							    		    			return false; \r\n");
		sb.append("						    				    } \r\n");
		sb.append("		        			     }else{\r\n");
		sb.append("		        			     		iszhengfan=\"zheng\";\r\n");
		sb.append("		        			     	}\r\n");
		sb.append("	    				    } else { \r\n");
		sb.append("	    				        alert(\"识别核心未加载，请先成功加载识别核心\"); \r\n");
		sb.append("	    				    } \r\n");
		sb.append("	     						FreeRecogKenal(); \r\n");
		sb.append("	     						return; \r\n");
		sb.append("	     						if(window.confirm(\"打开设备失败,是否显示演示效果?\")){ \r\n");
		sb.append("	      									objAIP.SetValue(\"Page\"+pagenum+\".idcardpicture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");    \r\n");
		sb.append("	        			     			objAIP.CurrPage(deletepagenum);//跳转到第二页  \r\n");
		sb.append("	        			     			return false;   \r\n");
		sb.append("	      							}else{ \r\n");
		sb.append("	      								 objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("	     			 						alert(\"打开设备失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("	     			 						return false;  \r\n");
		sb.append("	      							}   \r\n");
		sb.append("	     					}    \r\n");
		sb.append("	       				var statusret=CardReader_CMCC.MutiIdCardGetDeviceStatus();//获取设备状态    \r\n");
		sb.append("	     					if(statusret!=0){    \r\n");
		sb.append("	       			        objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("	     						alert(\"设备状态异常，异常信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("	     						return false;    \r\n");
		sb.append("	     					}    \r\n");
		sb.append("	     					    \r\n");
		sb.append("	     					var photoret=CardReader_CMCC.MutiIdCardPhotograph('C:/hotel_idcardinfo.jpg',1);    \r\n");
		sb.append("	     					if(photoret!=0){    \r\n");
		sb.append("	       			        objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("	     						alert(\"拍照出错，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("	     						return false;    \r\n");
		sb.append("	     					}    \r\n");
		sb.append("	     					CardReader_CMCC.MutiIdCardCloseDevice();//关闭设备    \r\n");
		sb.append("	     					objAIP.SetValue(\"Page\"+pagenum+\".idcardpicture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");    \r\n");
		sb.append("	     					objAIP.DeleteLocalFile(\"C:/hotel_idcardinfo.jpg\");  \r\n");
		sb.append("	       			     objAIP.CurrPage(deletepagenum);//跳转到第二页    \r\n");
		sb.append("       			}else{    \r\n");
		sb.append("       				alert(\"插入页失败!\");    \r\n");
		sb.append("       				return false;    \r\n");
		sb.append("       			}    \r\n");
		sb.append("       		}    \r\n");

		sb.append("     		    \r\n");
		sb.append("     		    \r\n");
		sb.append("     		//FT2000多功能身份采集仪    \r\n");
		sb.append("     		function addIdCardInfo(){    \r\n");
		sb.append("     			var objAIP=document.getElementById(\"HWPostil1\");    \r\n");
		sb.append("     			var doctype = objAIP.CurrDocType;      \r\n");
		sb.append("     			if(doctype==31){    \r\n");
		sb.append("     				alert(\"文档已盖章，不能修改！\");    \r\n");
		sb.append("     				return false;    \r\n");
		sb.append("     			}    \r\n");
		sb.append("     			var vRet = objAIP.Login(username,2, 65535,\"\",\"\");    \r\n");
		sb.append("     			var idcardtemplate=document.getElementById(\"身份证信息页\");    \r\n");
		sb.append("     			var data = idcardtemplate.value;    \r\n");
		sb.append("     			var pagenum = objAIP.PageCount;    \r\n");
		sb.append("     			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);    \r\n");
		sb.append("     			if(m==1){    \r\n");
		sb.append("       				pagenum = objAIP.PageCount;  \r\n");
		sb.append("       				var deletepagenum =  pagenum -1;   \r\n");
		sb.append("     				var openret=CardReader_CMCC.MutiIdCardOpenDevice(1000);//打开设备    \r\n");
		sb.append("   					if(openret!=0){ \r\n");
		sb.append("   						LoadRecogKenalDuKa(); \r\n");
		sb.append("   						if(objIDCardDuKa.IsLoaded) \r\n");
		sb.append("  { \r\n");
		sb.append("   if (!objIDCardDuKa.IsCardRead()) \r\n");
		sb.append("      { 	 \r\n");
		sb.append("  	var nRet = objIDCardDuKa.Read(\"C:/testtouxiang.bmp\"); \r\n");
		sb.append("  	if(nRet==0x90){ \r\n");
		sb.append("				var huoquname = objIDCardDuKa.GetName(); \r\n ");
		sb.append("    		objAIP.SetValue(\"Page\"+pagenum+\".name\",huoquname);  //姓名    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".sex\",objIDCardDuKa.GetSex()); //性别    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".people\",objIDCardDuKa.GetPeople()); //名族      \r\n ");
		sb.append("	  				var datestr = objIDCardDuKa.GetBirthDay(); \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".nian\",getDateStr(datestr,\"nian\")); //出生年月    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".yue\",getDateStr(datestr,\"yue\")); //出生年月    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".ri\",getDateStr(datestr,\"ri\")); //出生年月    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".address\",objIDCardDuKa.GetAddress()); //住址   \r\n ");
		sb.append("	  			var huoqucardno =  objIDCardDuKa.GetIDCode(); \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",huoqucardno); //身份证号    \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",objIDCardDuKa.GetAuthority());//签发机关   \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",objIDCardDuKa.GetIssueDay()+\"-\"+objIDCardDuKa.GetExpityDay());//有效期限   \r\n ");
		sb.append("	  				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:C:/testtouxiang.bmp\");//头像图片   \r\n ");
		sb.append("	 					objAIP.CurrPage(deletepagenum);//跳转到最后一页   \r\n ");
		sb.append("    				FreeRecogKenalDuKa(); \r\n ");
		sb.append("    				var danjuGuestname =objAIP.GetValueEx(\"guestname\",42,\"\",0,\"\"); \r\n ");
		sb.append("    				danjuGuestname = danjuGuestname.replace(/^\\s+|\\s+$/g,\"\"); \r\n ");
		sb.append("    				var danjuCardNo =objAIP.GetValueEx(\"cardNo\",42,\"\",0,\"\"); \r\n ");
		sb.append("    				danjuCardNo = danjuCardNo.replace(/^\\s+|\\s+$/g,\"\"); \r\n ");
		sb.append("    		if(danjuGuestname.indexOf(huoquname)==-1||danjuCardNo.indexOf(huoqucardno)==-1){ \r\n ");
		sb.append("    			alert(\"身份证信息与客户基本信息不一致，请检查\"); \r\n ");
		sb.append("    			objAIP.DeletePage(deletepagenum);    \r\n ");
		sb.append("    		} \r\n ");
		sb.append("    		return false; \r\n ");
		sb.append("  	} \r\n");
		sb.append("     else{ \r\n");
		sb.append("  		strResult=\"识别失败!,返回值：\"; \r\n");
		sb.append("                  strResult+=nRet; \r\n");
		sb.append("    			objAIP.DeletePage(deletepagenum);    \r\n ");
		sb.append("  	} \r\n");
		sb.append("    }else{ \r\n");
		sb.append("  		strResult=\"此卡已读取过！请放下一张...\"; \r\n");
		sb.append("    			objAIP.DeletePage(deletepagenum);    \r\n ");
		sb.append("    } \r\n");
		sb.append("  }else{ \r\n");
		sb.append("      strResult=\"核心未加载，请加载核心...\"; \r\n");
		sb.append("    			objAIP.DeletePage(deletepagenum);    \r\n ");
		sb.append("  } \r\n");
		sb.append("  alert(strResult); \r\n");
		sb.append("   						FreeRecogKenalDuKa(); \r\n");
		sb.append("   						return; \r\n");
		sb.append("   						if(window.confirm(\"打开设备失败,是否显示演示效果?\")){ \r\n");
		sb.append("    							objAIP.SetValue(\"Page\"+pagenum+\".name\",\"张三\");  //姓名    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".sex\",\"男\"); //性别    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".people\",\"汉\"); //名族      \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".nian\",\"1980\"); //出生年月    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".yue\",\"01\"); //出生年月    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".ri\",\"01\"); //出生年月    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".address\",\"广东省深圳市\"); //住址    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",\"110110111111111111\"); //身份证号    \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",\"广东省深圳市公安局\");//签发机关   \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",\"2012.01.01\"+\"-\"+\"2013.01.01\");//有效期限   \r\n");
		sb.append("   				  				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:C:/hotel_touxiang.jpg\");//头像图片   \r\n");
		sb.append("   				 				objAIP.CurrPage(deletepagenum);//跳转到最后一页   \r\n");
		sb.append("   				 				return false;  \r\n");
		sb.append("    						}else{ \r\n");
		sb.append("    							objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("    							alert(\"打开设备失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("    							return false;  \r\n");
		sb.append("    						} \r\n");
		sb.append("   					}    \r\n");
		sb.append("     				var statusret=CardReader_CMCC.MutiIdCardGetDeviceStatus();//获取设备状态    \r\n");
		sb.append("   					if(statusret!=0){    \r\n");
		sb.append("     			        objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("   						alert(\"设备状态异常，异常信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("   						return false;    \r\n");
		sb.append("   					}    \r\n");
		sb.append("   					var imgret=CardReader_CMCC.MutiIdCardGetImageMsg(11,'C:/hotel_idcardinfo.jpg');//拍照识别电子影印件信息    \r\n");
		sb.append("   					if(imgret!=0){    \r\n");
		sb.append("     			        objAIP.DeletePage(deletepagenum);    \r\n");
		sb.append("   						alert(\"拍照识别出错，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());    \r\n");
		sb.append("   						return false;    \r\n");
		sb.append("   					}    \r\n");
		sb.append("                    objAIP.SetValue(\"Page\"+pagenum+\".name\",CardReader_CMCC.MutiIdCardName);  //姓名    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".sex\",CardReader_CMCC.MutiIdCardSex); //性别    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".people\",CardReader_CMCC.MutiIdCardPeople); //名族    \r\n");
		sb.append("    				var datestr = CardReader_CMCC.MutiIdCardBirthday;    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".nian\",getDateStr(datestr,\"nian\")); //出生年月    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".yue\",getDateStr(datestr,\"yue\")); //出生年月    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".ri\",getDateStr(datestr,\"ri\")); //出生年月    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".address\",CardReader_CMCC.MutiIdCardAddress); //住址    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",CardReader_CMCC.MutiIdCardNumber); //身份证号    \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",CardReader_CMCC.MutiIdCardOrgans);//签发机关   \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",CardReader_CMCC.MutiIdCardSigndate+\"-\"+CardReader_CMCC.MutiIdCardValidterm);//有效期限   \r\n");
		sb.append("    				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");//头像图片    \r\n");
		sb.append("               objAIP.SetValue(\"Page1.guestname1\",\"\");  //姓名   \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.guestname1\",CardReader_CMCC.MutiIdCardName);  //姓名   \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.sex\",\"\");  //性别    \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.sex\",CardReader_CMCC.MutiIdCardSex);  //性别    \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.cardNO1\",\"\");  //身份证号      \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.cardNO1\",CardReader_CMCC.MutiIdCardNumber);  //身份证号       \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.birth\",\"\");  //出生年月日   \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.birth\",getDateStr(datestr,\"nian\")+\"年\"+getDateStr(datestr,\"yue\")+\"月\"+getDateStr(datestr,\"ri\")+\"日\");  //出生年月日   \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.address\",\"\"); //住址    \r\n");
		sb.append("    	   				objAIP.SetValue(\"Page1.address\",CardReader_CMCC.MutiIdCardAddress); //住址  \r\n");
		sb.append("   					CardReader_CMCC.MutiIdCardCloseDevice();//关闭设备    \r\n");
		sb.append("   					objAIP.DeleteLocalFile(\"C:/hotel_idcardinfo.jpg\");  \r\n");
		sb.append("     			    objAIP.CurrPage(deletepagenum);//跳转到最后一页    \r\n");
		sb.append("     			}else{    \r\n");
		sb.append("     				alert(\"插入页失败!\");    \r\n");
		sb.append("     				return false;    \r\n");
		sb.append("     			}    \r\n");
		sb.append("     		}  \r\n");
		sb.append("     		 \r\n");
		sb.append("     		function getDateStr(str,type){  \r\n");
		sb.append("       			if(str==\"长期\"){  \r\n");
		sb.append("       				return str;   \r\n");
		sb.append("       			}else if(str.length!=8){  \r\n");
		sb.append("       				alert(\"获取到的日期有误：\"+str);	  \r\n");
		sb.append("       				return false;  \r\n");
		sb.append("       			}  \r\n");
		sb.append("      			if(type==\"nian\"){  \r\n");
		sb.append("      				var ret = str.substring(0,4);  \r\n");
		sb.append("      				return ret;  \r\n");
		sb.append("      			}else if(type==\"yue\"){  \r\n");
		sb.append("      				var ret = str.substring(4,6);  \r\n");
		sb.append("      				if(ret<10){  \r\n");
		sb.append("      					return ret.substring(1,2);  \r\n");
		sb.append("      				}else{  \r\n");
		sb.append("      					return ret;  \r\n");
		sb.append("      				}  \r\n");
		sb.append("      			}else if(type==\"ri\"){  \r\n");
		sb.append("      				var ret = str.substring(6,8);  \r\n");
		sb.append("      				if(ret<10){  \r\n");
		sb.append("      					return ret.substring(1,2);  \r\n");
		sb.append("      				}else{  \r\n");
		sb.append("      					return ret;  \r\n");
		sb.append("      				}  \r\n");
		sb.append("      			}  \r\n");
		sb.append("      		}  \r\n");
		sb.append("       	function DateJiaDian(str){   \r\n");
		sb.append("       				if(str==\"长期\"){  \r\n");
		sb.append("       					return str;   \r\n");
		sb.append("       				}else if(str.length!=8){  \r\n");
		sb.append("       					alert(\"获取到的日期有误：\"+str);	  \r\n");
		sb.append("       					return false;  \r\n");
		sb.append("       				}  \r\n");
		sb.append("       				var nian = str.substring(0,4);   \r\n");
		sb.append("       				var yue = str.substring(4,6);   \r\n");
		sb.append("       				var ri = str.substring(6,8);   \r\n");
		sb.append("       				return nian+\".\"+yue+\".\"+ri;  \r\n");
		sb.append("       	} \r\n");

		
		//加入盖章功能的新版本新增的方法 开始
		sb.append("  		function addPrivateSeal(){       \r\n ");
		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");       \r\n ");
		sb.append("  			var l = objAIP.Login(\"\",3, 65535,\"\",\"http://192.168.1.61:8080/Seal/general/interface/\");       \r\n ");
		sb.append("  			if(l!=0){       \r\n ");
		sb.append("  				if(l==-200){       \r\n ");
		sb.append("  					alert(\"请插入key！\");       \r\n ");
		sb.append("  					return false;       \r\n ");
		sb.append("  				}else{       \r\n ");
		sb.append("  					alert(\"盖章登录失败！返回值为：\"+l);       \r\n ");
		sb.append("  					return false;       \r\n ");
		sb.append("  				}       \r\n ");
		sb.append("  			}       \r\n ");
		sb.append("  			var doctype = objAIP.CurrDocType;       \r\n ");
		sb.append("  			if(doctype!=31){       \r\n ");
		sb.append("  				if(openZancun==1){       \r\n ");
		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
		sb.append("                     }       \r\n ");
		sb.append("                  var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append(" 			   	objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);       \r\n ");
		sb.append("	  				var filepath=objAIP.PathName;       \r\n ");
		sb.append("  				 var deletepath=filepath;     \r\n ");
		sb.append("	  				var temp=filepath.split(\".\");       \r\n ");
		sb.append("	  				filepath=temp[0]+\".pdf\";       \r\n ");
		sb.append("	  				var currfileName =  temp[0].substring(temp[0].lastIndexOf(\"/\")+1,temp[0].length);       \r\n ");
		sb.append("	  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("	  				var myDate = new Date();       \r\n ");
		sb.append("            var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
		sb.append("            objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
		sb.append(" 						objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
		sb.append("	  				var res=objAIP.SaveTo(filepath,\"pdf\",0);       \r\n ");
		sb.append("  				 if(res!=0){     \r\n ");
		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				 }else{     \r\n ");
		sb.append("  				     alert(\"盖个人章保存出错！\");    \r\n ");
		sb.append("  				     return false;     \r\n ");
		sb.append("  				 }     \r\n ");
		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
		sb.append("	  				objAIP.LoadFile(filepath);       \r\n ");
		sb.append("  				}else{       \r\n ");
		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
		sb.append("             }       \r\n ");
		sb.append("                  var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append(" 			   	 objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);       \r\n ");
		sb.append("  					var myDate = new Date();       \r\n ");
		sb.append("  					var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
		sb.append("  					var savefilePath=savePath+\"local/\"+currfileName+\".pdf\";       \r\n ");
		sb.append("  					var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("                     var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
		sb.append("                     objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
		sb.append(" 					objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
		sb.append("  					var res=objAIP.SaveTo(savefilePath,\"pdf\",0);       \r\n ");
		sb.append("  				    if(res!=0){     \r\n ");
		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				    }else{     \r\n ");
		sb.append("  				      alert(\"盖个人章保存出错！\");    \r\n ");
		sb.append("  				      return false;     \r\n ");
		sb.append("  				    }     \r\n ");
		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
		sb.append("  					objAIP.LoadFile(savefilePath);       \r\n ");
		sb.append("  				}       \r\n ");
		sb.append("  			}       \r\n ");
		sb.append("  			var s1=objAIP.SetValue(\"SET_SEAL_TYPE_FORADD\",\"2\");//个人章       \r\n ");
		sb.append("  			objAIP.CurrAction=2568;       \r\n ");
		sb.append("  		}       \r\n ");
		sb.append("  		       \r\n ");
		sb.append("  		function addPublicSeal(){       \r\n ");
		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");       \r\n ");
		sb.append("  			var l = objAIP.Login(\"\",3, 65535,\"\",\"http://192.168.1.61:8080/Seal/general/interface/\");       \r\n ");
		sb.append("  			if(l!=0){       \r\n ");
		sb.append("  				if(l==-200){       \r\n ");
		sb.append("  					alert(\"请插入key！\");       \r\n ");
		sb.append("  					return false;       \r\n ");
		sb.append("  				}else{       \r\n ");
		sb.append("  					alert(\"盖章登录失败！返回值为：\"+l);       \r\n ");
		sb.append("  					return false;       \r\n ");
		sb.append("  				}       \r\n ");
		sb.append("  			}       \r\n ");
		sb.append("  			var doctype = objAIP.CurrDocType;       \r\n ");
		sb.append("  			if(doctype!=31){       \r\n ");
		sb.append("  				if(openZancun==1){       \r\n ");
		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
		sb.append("                     }       \r\n ");
		sb.append("                  var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append(" 			   	objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);       \r\n ");
		sb.append("	  				var filepath=objAIP.PathName;       \r\n ");
		sb.append("  				 var deletepath=filepath;     \r\n ");
		sb.append("	  				var temp=filepath.split(\".\");       \r\n ");
		sb.append("	  				filepath=temp[0]+\".pdf\";       \r\n ");
		sb.append("	  				var currfileName =  temp[0].substring(temp[0].lastIndexOf(\"/\")+1,temp[0].length);       \r\n ");
		sb.append("	  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("	  				var myDate = new Date();       \r\n ");
		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,4);       \r\n ");
		sb.append("	  				var res=objAIP.SaveTo(filepath,\"pdf\",0);       \r\n ");
		sb.append("  				 if(res!=0){     \r\n ");
		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				 }else{     \r\n ");
		sb.append("  				     alert(\"盖公章保存出错！\");    \r\n ");
		sb.append("  				     return false;     \r\n ");
		sb.append("  				 }     \r\n ");
		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
		sb.append("	  				objAIP.LoadFile(filepath);       \r\n ");
		sb.append("  				}else{       \r\n ");
		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
		sb.append("                     }       \r\n ");
		sb.append("                     var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append(" 			        objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);       \r\n ");
		sb.append("  					var myDate = new Date();       \r\n ");
		sb.append("  					var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
		sb.append("  					var savefilePath=savePath+\"local/\"+currfileName+\".pdf\";       \r\n ");
		sb.append("  					var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("                     var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
		sb.append("                     objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
		sb.append(" 					objAIP.ExportEditNodeValue(\"\",infpath,4);       \r\n ");
		sb.append("  					var res=objAIP.SaveTo(savefilePath,\"pdf\",0);       \r\n ");
		sb.append("  				    if(res!=0){     \r\n ");
		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				    }else{     \r\n ");
		sb.append("  				       alert(\"盖公章保存出错！\");    \r\n ");
		sb.append("  				       return false;     \r\n ");
		sb.append("  				    }     \r\n ");
		sb.append("  				    objAIP.CloseDoc(0);     \r\n ");
		sb.append("  					objAIP.LoadFile(savefilePath);       \r\n ");
		sb.append("  				}       \r\n ");
		sb.append("  			}       \r\n ");
		sb.append("  			var s1=objAIP.SetValue(\"SET_SEAL_TYPE_FORADD\",\"1\");//公章       \r\n ");
		sb.append("  			objAIP.CurrAction=2568;       \r\n ");
		sb.append("  		}       \r\n ");
		//加入盖章功能的新版本新增的方法 结束
		
		//老版本的暂存和上传方法 开始
//		sb.append(" 		function saveTemp(){\r\n");
//		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
//		sb.append(" 			var filepath=objAIP.PathName;\r\n");
//		sb.append(" 			if(openZancun==1){\r\n");
//		sb.append(" 				objAIP.SaveTo(filepath,\"aip\",0);\r\n");
//		sb.append(" 			}else{\r\n");
//		sb.append(" 				var myDate = new Date();\r\n");
//		sb.append(" 				var savefilePath=savePath+\"/local/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".aip\";\r\n");
//		sb.append(" 			    objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);\r\n");
//		sb.append(" 				objAIP.SaveTo(savefilePath,\"aip\",0);\r\n");
//		sb.append(" 			}\r\n");
//		sb.append(" 			openZancun=1;\r\n");
//		sb.append(" 		}\r\n");
//		sb.append(" 		function saveUpload(){\r\n");
//		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
//		sb.append(" 			var filepath=objAIP.PathName;\r\n");
//		sb.append("             if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){        \r\n");
//		sb.append(" 			   objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);\r\n");
//		sb.append("             }\r\n");
//		sb.append(" 			if(openZancun==1){\r\n");
//		sb.append(" 				var deletepath=filepath;\r\n");
//		sb.append(" 				filepath=filepath.replace(\"local\",\"remote\");\r\n");
//		sb.append(" 				var temp=filepath.split(\".\");\r\n");
//		sb.append(" 				filepath=temp[0]+\".pdf\";\r\n");
//		sb.append(" 				var infpath=temp[0]+\".inf\";\r\n");
//		sb.append("                 var myDate = new Date();\r\n");
//		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
//		sb.append("                 var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);\r\n");
//		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,4);\r\n");
//		sb.append(" 				var res=objAIP.SaveTo(filepath,\"pdf\",0);\r\n");
//		sb.append(" 				if(res!=0){\r\n");
//		sb.append(" 					objAIP.DeleteLocalFile(deletepath);\r\n");
//		sb.append(" 				}\r\n");
//		sb.append(" 			}else{\r\n");
//		sb.append(" 				var myDate = new Date();\r\n");
//		sb.append(" 				var savefilePath=savePath+\"remote/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".pdf\";\r\n");
//		sb.append(" 				var infpath=savePath+\"remote/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".inf\";\r\n");
//		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
//		sb.append("                 var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);\r\n");
//		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,4);\r\n");
//		sb.append(" 				objAIP.SaveTo(savefilePath,\"pdf\",0);\r\n");
//		sb.append(" 			}\r\n");
//	    sb.append(" 			window.opener=null;\r\n");
//	    sb.append(" 			window.open('', '_self', '');\r\n");
//		sb.append(" 			window.close();\r\n");
//		sb.append(" 		}\r\n");
		//老版本的暂存和上传方法 结束
		
		
		
		//加入盖章功能的新版本的上传方法 开始  打印功能没有用到暂存
		sb.append(" 		function saveUpload(){\r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
		sb.append(" 			var filepath=objAIP.PathName;\r\n");
		sb.append("  			var doctype = objAIP.CurrDocType;     \r\n ");
//		sb.append("  			if(doctype==31){     \r\n ");
//		sb.append("  				 var deletepath=filepath;     \r\n ");
//		sb.append("  				 filepath=filepath.replace(\"local\",\"remote\");     \r\n ");
//		sb.append("  				 var res=objAIP.SaveTo(filepath,\"pdf\",0);     \r\n ");
//		sb.append("  				 if(res!=0){     \r\n ");
//		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
//		sb.append("  				 }else{     \r\n ");
//		sb.append("  				     alert(\"上传保存出错！\");    \r\n ");
//		sb.append("  				     return false;     \r\n ");
//		sb.append("  				 }     \r\n ");
//		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
//	    sb.append(" 			     window.opener=null;\r\n");
//	    sb.append(" 			     window.open('', '_self', '');\r\n");
//		sb.append(" 			     window.close();\r\n");
//		sb.append("  			}     \r\n ");
		sb.append("             if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){        \r\n");
		sb.append(" 			   objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);\r\n");
		sb.append("             }\r\n");
		sb.append(" 			if(openZancun==1){\r\n");
		sb.append(" 				var deletepath=filepath;\r\n");
		sb.append(" 				filepath=filepath.replace(\"local\",\"remote\");\r\n");
		sb.append(" 				var temp=filepath.split(\".\");\r\n");
		sb.append(" 				filepath=temp[0]+\".pdf\";\r\n");
		sb.append(" 				var infpath=temp[0]+\".inf\";\r\n");
		sb.append("                 var myDate = new Date();\r\n");
		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
		sb.append("                 var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);\r\n");
		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,4);\r\n");
		sb.append(" 				var res=objAIP.SaveTo(filepath,\"pdf\",0);\r\n");
		sb.append(" 				if(res!=0){\r\n");
		sb.append(" 					objAIP.DeleteLocalFile(deletepath);\r\n");
		sb.append(" 				}\r\n");
		sb.append(" 			}else{\r\n");
		sb.append(" 				var myDate = new Date();\r\n");
		sb.append("  				var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
		sb.append("  				var savefilePath=savePath+\"remote/\"+currfileName+\".pdf\";       \r\n ");
		sb.append("  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
		sb.append("                 var DJ_IN_REMARK = document.getElementById(\"DJ_IN_REMARK\").value;\r\n");
		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_REMARK\",DJ_IN_REMARK);\r\n");
		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,4);\r\n");
		sb.append(" 				objAIP.SaveTo(savefilePath,\"pdf\",0);\r\n");
		sb.append(" 			}\r\n");
	    sb.append(" 			window.opener=null;\r\n");
	    sb.append(" 			window.open('', '_self', '');\r\n");
		sb.append(" 			window.close();\r\n");
		sb.append(" 		}\r\n");
		//加入盖章功能的新版本的上传方法 结束  打印功能没有用到暂存
		
		
		sb.append(" 	function setbikuan(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.CurrPenWidth = -1; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function setyanse(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.CurrPenColor = -1; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function setqueren(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.ShowFullScreen = 0;  \r\n");
		sb.append("    		  objAIP.CurrAction=1; \r\n");
		sb.append(" 				 \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function printdoc(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		
//		sb.append(" 				if(currdispayName==\"业务变更单\"){  \r\n ");
//		sb.append("					 var kongbaitemplate=document.getElementById(\"空白页\");   \r\n ");
//		sb.append("					 var data = kongbaitemplate.value;     \r\n ");
//		sb.append("					objAIP.SetBackgroundDoc(\"STRDATA:\"+data,\"\",0); \r\n ");
//		sb.append(" 			} \r\n ");
		
//		sb.append(" 				objAIP.PrintDoc(1,1);  \r\n");
		sb.append(" 				var pagenum = objAIP.PageCount;  \r\n");
		sb.append(" 				pagenum = 1;  \r\n");
		sb.append(" 				var printret = objAIP.PrintDocEx(\"\",1,1,1,1,pagenum,1,1,1,0,0);  \r\n");
		sb.append(" 				if(printret<=0){  \r\n");
		sb.append(" 					alert(\"打印失败!\"); \r\n");
		sb.append(" 				} \r\n");
		sb.append(" 		} \r\n");
		
		
		sb.append(" 		var iszhengfan = \"zheng\"; \r\n");
		sb.append(" 		function zhengjianpaizhao(){ \r\n");
		sb.append(" 			showModalDialog(\"gaopaiyi.htm\",\"\",\"dialogWidth:1000px;dialogHeight:600px;scroll:no;status:no\"); \r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 			var pageCount=objAIP.PageCount; \r\n");
		sb.append(" 			objAIP.Login(\"HWSEALDEMO\", 4, 65535, \"DEMO\", \"\"); \r\n");
		sb.append(" 			if(iszhengfan==\"zheng\"){ \r\n");
		sb.append(" 				objAIP.InsertEmptyPage(pageCount,0,0,0); \r\n");
		sb.append(" 				objAIP.InsertPicture(\"gaopaiyi1\",\"c:/gaopaiyi.jpg\",pageCount,25000,10000,20); \r\n");
		sb.append(" 				iszhengfan=\"fan\"; \r\n");
		sb.append(" 				zhengjianpage = pageCount; \r\n");
		sb.append(" 				objAIP.CurrPage=pageCount; \r\n");
		sb.append(" 			}else{ \r\n");
		sb.append(" 				objAIP.InsertPicture(\"gaopaiyi2\",\"c:/gaopaiyi.jpg\",zhengjianpage,25000,30000,20); \r\n");
		sb.append("				iszhengfan=\"zheng\"; \r\n");
		sb.append("				objAIP.CurrPage=zhengjianpage; \r\n");
		sb.append(" 			}	 \r\n");
		sb.append(" 		} \r\n");



		
		sb.append(" 		function fujianpaizhao(){ \r\n");
		sb.append(" 			showModalDialog(\"gaopaiyi.htm\",\"\",\"dialogWidth:1000px;dialogHeight:600px;scroll:no;status:no\"); \r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 			var pageCount=objAIP.PageCount; \r\n");
		sb.append(" 			objAIP.Login(\"HWSEALDEMO\", 4, 65535, \"DEMO\", \"\"); \r\n");
		sb.append(" 			objAIP.InsertEmptyPage(pageCount,0,0,0); \r\n");
		sb.append(" 			objAIP.InsertPicture(\"gaopaifujian\",\"c:/gaopaiyi.jpg\",pageCount,0,0,100); \r\n");
		sb.append(" 			objAIP.CurrPage=pageCount;	 \r\n");
		sb.append(" 		} \r\n");
		
		
		sb.append(" 		 function HWPostil1_NotifyFullScreen(){ \r\n");
		sb.append("  					var objAIP=document.getElementById(\"HWPostil1\");  \r\n");
		sb.append("  					if(objAIP.ShowFullScreen == 0){ \r\n");
		sb.append("  						objAIP.CurrAction=1;  \r\n");
		sb.append("  					  objAIP.JSValue = 0;  \r\n");
		sb.append("  					} \r\n");
		sb.append("  			}  \r\n");
		
		sb.append(" 		function HWPostil1_NotifyCtrlReady(){\r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n");
		sb.append(" 			objAIP.JSEnv = 1;						\r\n ");
		sb.append(" 			objAIP.ShowDefMenu = 0 ;						\r\n");
		sb.append("  			objAIP.ShowScrollBarButton =2;			\r\n");
		sb.append("  			objAIP.ShowToolBar = 0;	\r\n");
		sb.append("  			objAIP.SilentMode = 1;	\r\n ");
		sb.append("  			objAIP.SetPageMode(2,100);	\r\n ");
		sb.append("  			objAIP.SetPageMode(16,1);	\r\n ");
		sb.append("  			ocxReady=ocxReady+1;\r\n");
		sb.append(" 			if(ocxReady==2){\r\n");
		sb.append(" 				comparisonTemplate();\r\n");
		sb.append(" 				setTemplateTable();\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 		}\r\n");
		sb.append("   function HWPostil1_NotifyBeforeAction(lActionType,lType,strName,strValue){  \r\n ");
		sb.append("     			if(lActionType==9){  \r\n ");
		sb.append("     				var objAIP=document.getElementById(\"HWPostil1\"); \r\n ");
		sb.append("     				if(strName==\"Page1.PredefineSignArea\"){ \r\n ");
		sb.append(" 	    				 var phonearea = objAIP.GetValueEx(\"Page1.PhoneWriteArea\",12,\"\",0,\"\"); \r\n ");
		sb.append(" 	    				if(phonearea==\"\"){ \r\n ");
		sb.append(" 	    				 	var phonearea22 = objAIP.GetValueEx(\"Page2.PhoneWriteArea\",12,\"\",0,\"\"); \r\n ");
		sb.append(" 	    					if(phonearea22==\"\"){ \r\n ");
		sb.append(" 	    						objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    						objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    						objAIP.ShowFullScreen = 0; \r\n ");
		sb.append(" 	    					}else{ \r\n ");
		sb.append(" 	    						objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    						objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    						objAIP.SetValue(\"Page2.PhoneWriteArea\",\":PROP:ACTIVATE:1\"); \r\n ");
		sb.append(" 	    					} \r\n ");
		sb.append(" 	    				}else{ \r\n ");
		sb.append(" 	    					objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    					objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    					objAIP.SetValue(\"Page1.PhoneWriteArea\",\":PROP:ACTIVATE:1\"); \r\n ");
		sb.append(" 	    				} \r\n ");
		sb.append(" 	    			}else if(strName==\"Page2.PredefineSignArea\"){ \r\n ");
		sb.append(" 	    				 var phonearea = objAIP.GetValueEx(\"Page2.PhoneWriteArea\",12,\"\",0,\"\"); \r\n ");
		sb.append(" 	    				if(phonearea==\"\"){ \r\n ");
		sb.append(" 	    					objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    					objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    					objAIP.ShowFullScreen = 0; \r\n ");
		sb.append(" 	    				}else{ \r\n ");
		sb.append(" 	    					objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    					objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    					objAIP.SetValue(\"Page2.PhoneWriteArea\",\":PROP:ACTIVATE:1\"); \r\n ");
		sb.append(" 	    				} \r\n ");
		sb.append(" 	    			}else{ \r\n ");
		sb.append(" 	    				  objAIP.CurrAction=1;  \r\n ");
		sb.append(" 	    					objAIP.JSValue = 0; \r\n ");
		sb.append(" 	    					objAIP.ShowFullScreen = 0; \r\n ");
		sb.append(" 	    			} \r\n ");
		sb.append("     			}  \r\n ");
		sb.append("     } \r\n ");
		sb.append("    function setxieyi(){ \r\n");
		sb.append("    if(currtemplateName==null||currtemplateName==\"\"){alert(\"请先选择模版！\");return ;} \r\n");
		sb.append("    	if(!isSetXieyi){ \r\n");
		sb.append("    		 	var xieyiStr=document.getElementById(currtemplateName).value; \r\n");
		sb.append("    		 	var xieyiarr=eval(xieyiStr); \r\n");
		sb.append("    		 	var xieyiSelect=document.getElementById(\"xiyiSelect\"); \r\n");
		sb.append("    		 	xieyiSelect.options.length = 0;  \r\n");
		sb.append("    		 	for(var i=0;i<xieyiarr.length;i++){ \r\n");
		sb.append("    		 		var xieyi=xieyiarr[i]; \r\n");
		sb.append("    		 		var opp = new Option(xieyi.xieyiname,xieyi.xieyiid); \r\n");
		sb.append("    		 		opp.id=xieyi.xieyiid+\"Option\"; \r\n");
		sb.append("    		 		xieyiSelect.add(opp); \r\n");
		sb.append("    		 	} \r\n");
		sb.append("    		 	isSetXieyi=true; \r\n");
		sb.append("    	} \r\n");
		sb.append("    	document.getElementById(\"aipDiv\").style.visibility=\"hidden\";//visibility=\"visible\"; \r\n");
		sb.append("    	ShowDialog(\"info\");	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   function ShowDialog(id){	 \r\n");
		sb.append("   var $ = function(id) {return document.getElementById(id);};	 \r\n");
		sb.append("   $(\"overlay\").style.display = 'block';	 \r\n");
		sb.append("   $(id).style.display = 'block';	 \r\n");
		sb.append("   var bb=(document.compatMode && document.compatMode!=\"BackCompat\") ? document.documentElement : document.body;	 \r\n");
		sb.append("   if(document.compatMode && document.compatMode!=\"BackCompat\"){	 \r\n");
		sb.append("   	$(\"overlay\").style.width = bb.scrollWidth+\"px\";	 \r\n");
		sb.append("   	$(\"overlay\").style.height = bb.scrollHeight+\"px\";	 \r\n");
		sb.append("   }else{	 \r\n");
		sb.append("   	$(\"overlay\").style.width = bb.scrollWidth+\"px\";	 \r\n");
		sb.append("   	$(\"overlay\").style.height = bb.scrollHeight+\"px\";	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   $(id).style.left = ((bb.offsetWidth - $(id).offsetWidth)/2)+\"px\";	 \r\n");
		sb.append("   $(id).style.top  = (90 + bb.scrollTop)+\"px\";	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   function HideDialog(id){	 \r\n");
		sb.append("   	var $ = function(id) {return document.getElementById(id);};	 \r\n");
		sb.append("   	$(\"overlay\").style.display = 'none';	 \r\n");
		sb.append("   	$(id).style.display = 'none';	 \r\n");
		sb.append("   	document.getElementById(\"aipDiv\").style.visibility=\"visible\";	 \r\n");
		sb.append("   	var xieyiSelect=document.getElementById(\"xiyiSelect\");	 \r\n");
		sb.append("   	var objAIP=document.getElementById(\"HWPostil1\"); 	 \r\n");
		sb.append("   	var xuanzhongXieyi=\"\"; 	 \r\n");
		sb.append("   	while(xieyiSelect.selectedIndex>=0){ 	 \r\n");
		sb.append("   		xuanzhongXieyi=xuanzhongXieyi+xieyiSelect.value+\",\"; 	 \r\n");
		sb.append("   		xieyiSelect.remove(xieyiSelect.selectedIndex);   	 \r\n");
		sb.append("   	} 	 \r\n");
		sb.append("   	var xieyis=xuanzhongXieyi.split(\",\"); 	 \r\n");
		sb.append("   	objAIP.Login(username,2, 65535,\"\",\"\"); 	 \r\n");
		sb.append("   	for(var i=0;i<xieyis.length-1;i++){ 	 \r\n");
		sb.append("   		objAIP.MergeFile(objAIP.PageCount,savePath+\"/\"+modelfolder+\"/\"+xieyis[i]); 	 \r\n");
		sb.append("   	} 	 \r\n");
		sb.append("   } 	 \r\n");
		sb.append(" 	</script>\r\n");
		sb.append(" 	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=NotifyFullScreen>\r\n ");
		sb.append(" 		 HWPostil1_NotifyFullScreen();\r\n ");
		sb.append(" 	</SCRIPT>\r\n ");
		sb.append(" 	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=NotifyCtrlReady>\r\n");
		sb.append(" 		 HWPostil1_NotifyCtrlReady();\r\n");
		sb.append(" 	</SCRIPT>\r\n");
		sb.append("  	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=JSNotifyBeforeAction(lActionType,lType,strName,strValue)> \r\n");
		sb.append("  		 HWPostil1_NotifyBeforeAction(lActionType,lType,strName,strValue); \r\n");
		sb.append("  	</SCRIPT> \r\n");
		return sb.toString();
	}
	
	public static String getBodyStr(List<ModelFileVo> masterplates,List<Masterplatejudgep> masterplateJudges,List<ModelXieyiVo> modelXieyis){
		StringBuffer sb = new StringBuffer();
		sb.append(" <body onload=\"onLoad()\" language=javascript  oncontextmenu = \"return false;\"> \r\n");
		sb.append(" 	<form id=\"business\" method=\"post\"> \r\n");
		sb.append("		<input type=\"hidden\" id=\"templateInfo\" name=\"templateInfo\" value=\"").append(getBodyTemplateInfoStr(masterplates)).append("\">\r\n");
		sb.append(getBodyHiddenStr(masterplates,masterplateJudges,modelXieyis));
		sb.append(" 	</form> \r\n");
		sb.append(" 	<div id=\"outerDiv\">\r\n");
		sb.append(" 		<div id=\"headerDiv\">\r\n");
		//sb.append(" 			<span>&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" id=\"TemplateButton\" value=\"显示模板\"   onclick=\"showTemplateDiv()\"></span>\r\n");
		sb.append(" 		    <span><image id=\"TemplateButton\" src=\"images/001.gif\" onclick=\"showTemplateDiv()\"></span>\r\n");
		sb.append(" 			<b><span id=\"message\"></span></b>\r\n");
		sb.append(" 		</div>\r\n");
		sb.append(" 		<div id=\"TemplateDiv\">\r\n");
		sb.append(" 		</div>\r\n");
		sb.append("  		<div id=\"mainDiv\" >\r\n");
		sb.append("  			<div id=\"aipDiv\" align=\"center\">\r\n");
		sb.append("  				<OBJECT id=HWPostil1 classid=clsid:FF1FE7A0-0578-4FEE-A34E-FB21B277D561 style=\"width:90%;height:600px\"></OBJECT>\r\n");
		//加入身份证功能的新版本  读取二代证控件  开始
		sb.append("	                    <OBJECT id=CardReader_CMCC classid=clsid:D506E603-2C1C-4370-8D26-4563721C2810 style=\"width:0;height:0\"></OBJECT>   \r\n");
		sb.append("	                    <OBJECT classid=\"clsid:2DEFFB1F-4F4C-41B6-930A-63BE16732D61\" id=\"objIDCardDuKa\" width=\"0\" height=\"0\"></OBJECT>   \r\n");
		sb.append("	                    <OBJECT classid=\"clsid:10EC554B-357B-4188-9E5E-AC5039454D8B\" id=\"objIDCard\" width=\"0\" height=\"0\"></OBJECT>   \r\n");
		//加入身份证功能的新版本  读取二代证控件  结束
		sb.append("  			</div>\r\n");
		sb.append("  			<div  id=\"menuBarAIP\" align=\"center\">\r\n");
//		sb.append("  			          <strong>备注:&nbsp;</strong>\r\n");
		sb.append("  			         <input type=\"hidden\" id=\"DJ_IN_REMARK\" size=\"20\">\r\n");
//		sb.append("  					  &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
//		sb.append("                        <input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setbikuan\" value=\"笔宽\" onclick=\"setbikuan()\">  \r\n");
//		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setyanse\" value=\"颜色\" onclick=\"setyanse()\">  \r\n");
//		sb.append("     					&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
		sb.append("                         <input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setbikuan\" value=\"协议\" onclick=\"setxieyi()\">  \r\n");
//		sb.append("		 					<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"huodong\" value=\"添加协议\" onclick=\"addHuoDong()\">\r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"idcardbutton\" value=\"身份证拍照\" onclick=\"addIdCardImg()\">   \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"idcardbutton\" value=\"身份证识别\" onclick=\"addIdCardInfo()\">   \r\n");
		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\"  value=\"证件照\" onclick=\"zhengjianpaizhao()\"> \r\n");
		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\"  value=\"附件照\" onclick=\"fujianpaizhao()\"> \r\n");
		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"zhongdianbutton\" value=\"标注\" onclick=\"biaozhu()\">   \r\n");
		sb.append("     					&nbsp;&nbsp; \r\n");
		sb.append("		 					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"qianzi\" value=\"签字\" onclick=\"handWrite()\">\r\n");
		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setqueren\" value=\"确认\" onclick=\"setqueren()\">  \r\n");
//		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"lookdanju\" value=\"查看\" onclick=\"lookdanju()\">  \r\n");
		//加入盖章功能的新版本的盖个人章和公章按钮 开始
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"privatesealbutton\" value=\"盖个人章\" onclick=\"addPrivateSeal()\">   \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"publicsealbutton\" value=\"盖公章\" onclick=\"addPublicSeal()\">   \r\n");
		//加入盖章功能的新版本的盖个人章和公章按钮 结束
		
		
		sb.append("		 					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"upload\" value=\"上传\" onclick=\"saveUpload()\">\r\n");
		sb.append("     					&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"printdoc\" value=\"打印\" onclick=\"printdoc()\">  \r\n");
		sb.append("  			</div>\r\n");
		sb.append("  		</div>\r\n");
		sb.append(" 	</div>\r\n");
		sb.append("	<div id=\"overlay\"></div>\r\n");
		sb.append("	<div id=\"info\" class=\"ModalDialog\" style=\"width: 400px;\">\r\n");
		sb.append("		<div class=\"header\">\r\n");
		sb.append("			<span class=\"title\">协议选择</span>\r\n");
		sb.append("		</div>\r\n");
		sb.append("		<div id=\"info_body\" class=\"body\" align=\"center\">\r\n");
		sb.append("			<select id=\"xiyiSelect\" name=\"xiyiSelect\" multiple size=\"6\" style=\"width: 400px;\"></select>\r\n");
		sb.append("		</div>\r\n");
		sb.append("		<div id=\"footer\" class=\"footer\">\r\n");
		sb.append("			<input class=\"BigButton\" onclick=\"HideDialog('info')\" type=\"button\"	value=\"确定\" />\r\n");
		sb.append("		</div>\r\n");
		sb.append("	</div>\r\n");
		sb.append(" </body>\r\n");
		return sb.toString();
	}
	
	public static String getBodyTemplateInfoStr(List<ModelFileVo> masterplates){
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		for(ModelFileVo masterplate : masterplates){
			sb.append("{");
			sb.append("'name':'").append(masterplate.getModel_id()).append("','display':'").append(masterplate.getModel_name()).append("'");
			sb.append("},");
		}
		if(sb.lastIndexOf(",")!=-1){
			sb.deleteCharAt(sb.lastIndexOf(","));
		}
		sb.append("]");
		return sb.toString();
	}
	
	public static String getBodyHiddenStr(List<ModelFileVo> masterplates,List<Masterplatejudgep> masterplateJudges,List<ModelXieyiVo> modelXieyis){
		StringBuffer sb = new StringBuffer();
		for(ModelFileVo masterplate : masterplates){
			StringBuffer xieyi=new StringBuffer();
			xieyi.append("[");
			for(ModelXieyiVo i:modelXieyis){
				if(i.getModel_id().equals(masterplate.getModel_id())){
					xieyi.append("{'xieyiid':'").append(i.getXieyi_id()).append("','xieyiname':'").append(i.getXieyi_name());
					xieyi.append("'},");
				}
			}
			if(xieyi.lastIndexOf(",")!=-1){
				xieyi.deleteCharAt(xieyi.lastIndexOf(","));
			}
			xieyi.append("]");
			sb.append("<input type=\"hidden\" id=\"").append(masterplate.getModel_id()).append("\" value=\"").append(xieyi.toString()).append("\">\r\n");
			sb.append("<input type=\"hidden\" id=\"").append(masterplate.getModel_id()).append("TaoDa\" value=\"").append(masterplate.getMultipart()).append("\">\r\n");
			sb.append("<input type=\"hidden\" id=\"").append(masterplate.getModel_id()).append("Data\" value=\"").append(masterplate.getField_data()).append("\">\r\n");
			sb.append("<input type=\"hidden\" id=\"").append(masterplate.getModel_id()).append("Comparison\"  name=\"").append(masterplate.getModel_id()).append("Comparison\"  value=\"").append(getMasterplateJudgeStr(masterplate.getModel_id(), masterplateJudges)).append("\">\r\n");
		}
		sb.append("<input type=\"hidden\" id=\"空白页\" value=\"").append(ModelData.kongbaidata).append("\">\r\n");
		sb.append("\r\n");
		sb.append("<input type=\"hidden\" id=\"协议页\" value=\"").append(ModelData.xieyidata).append("\">\r\n");
		sb.append("\r\n");
		sb.append("<input type=\"hidden\" id=\"身份证图片页\" value=\"").append(ModelData.cardpicturedata).append("\">");
		sb.append("\r\n");
		
		return sb.toString();
	}
	
	
	public static String getMasterplateJudgeStr(int masterplateid,List<Masterplatejudgep> masterplateJudges){
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		for(Masterplatejudgep masterplateJudge : masterplateJudges){
			if(masterplateJudge.getMaster_platecid().equals(Integer.toString(masterplateid))){
				sb.append("{");
				sb.append("'name':'").append(masterplateJudge.getC_name()).append("','display':'").append(masterplateJudge.getC_value()).append("'");
				sb.append("},");
			}
		}
		if(sb.lastIndexOf(",")!=-1){
			sb.deleteCharAt(sb.lastIndexOf(","));
		}
		sb.append("]");
		return sb.toString();
	}
	
}
