package com.dj.hotelApi;

import java.util.List;

import com.dj.seal.modelFile.vo.ModelFileVo;
import com.dj.seal.modelFile.vo.ModelXieyiVo;

public class EditHtmlCodeBak {
	private static String modelfolder="modelfolder";
	//联通
	public static String getAllCode(List<ModelFileVo> masterplates,List<ModelXieyiVo> modelXieyis,String topcompanyname,String yytName){
		StringBuffer sb = new StringBuffer();
		sb.append("<html>\r\n<head>\r\n<META HTTP-EQUIV=\"content-type\" CONTENT=\"text/html; charset=gb2312\">\r\n");
		sb.append(getStyleStr());
		sb.append("<title>办理页面</title>\r\n");
		sb.append(getScriptStr(topcompanyname,yytName));
		sb.append("</head>\r\n");
		sb.append(getBodyStr(masterplates,modelXieyis));
		sb.append("</html>");
		return sb.toString();
	}
	
	
	public static String getStyleStr(){
		StringBuffer sb = new StringBuffer();
		sb.append("   <style> \r\n");
		sb.append("     .btn{ \r\n");
		sb.append("    BORDER-RIGHT: #7b9ebd 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7b9ebd 1px solid; PADDING-LEFT: 2px; FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#ffffff, EndColorStr=#cecfde); BORDER-LEFT: #7b9ebd 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #7b9ebd 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseout{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #9f9fa0 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #9f9fa0 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#f3f3f3, EndColorStr=#d9d9d9); BORDER-LEFT: #9f9fa0 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #9f9fa0 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseover{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #7EBF4F 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7EBF4F 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#8dda00, EndColorStr=#639800); BORDER-LEFT: #7EBF4F 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #7EBF4F 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mousedown \r\n");
		sb.append("    { \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #FFE400 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #FFE400 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#CC3300, EndColorStr=#CC3300); BORDER-LEFT: #FFE400 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #FFE400 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("    .btn1_mouseup{ \r\n");
		sb.append("    height:35px;BORDER-RIGHT: #7EBF4F 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #7EBF4F 1px solid; PADDING-LEFT: 2px; font-weight: bold;FONT-SIZE: 16px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#8dda00, EndColorStr=#639800); BORDER-LEFT: #7EBF4F 1px solid; CURSOR: hand; COLOR: #FFFFFF; PADDING-TOP: 2px; BORDER-BOTTOM: #7EBF4F 1px solid \r\n");
		sb.append("    } \r\n");
		sb.append("     .STYLE1 { \r\n");
		sb.append(" 			font-size: 22px; \r\n");
		sb.append(" 			font-weight: bold; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		body{ \r\n");
		sb.append(" 			margin:0px; \r\n");
		sb.append(" 			font-family:\"微软雅黑\",\"雅黑\"; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 			background-color:\"#FDF5E6\"; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		span{ \r\n");
		sb.append(" 			width:23%; \r\n");
		sb.append(" 			text-align=\"right\"; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		 \r\n");
		sb.append(" 		a:link{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #FFFFFF;color: black; text-decoration: none; } \r\n");
		sb.append(" 		a:visited{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #FFFFFF; color: #639800; text-decoration: none;} \r\n");
		sb.append(" 		a:hover{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #639800; color: white; text-decoration: none;} \r\n");
		sb.append(" 		a:active{FONT-SIZE:15px;font-family:\"微软雅黑\",\"雅黑\";background: #639800; color: white; text-decoration: none;}		 \r\n");
		sb.append(" \r\n");
		sb.append(" 		#outerDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#headerDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:30px; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#middleDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#zancunDiv{ \r\n");
		sb.append(" 			width:20%; \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 			float:left; \r\n");
		sb.append(" 			overflow:auto; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#zancunTable{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			boder:1px; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#banliDiv{ \r\n");
		sb.append(" 			height:100%; \r\n");
		sb.append(" 			margin:0; \r\n");
		sb.append(" 			float:left; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#TemplateDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			float:left; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#menuBarAIP{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:10%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#mainDiv{ \r\n");
		sb.append(" 			width:100%; \r\n");
		sb.append(" 			height:90%; \r\n");
		sb.append(" 			margin:0px; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		#aipDiv{ \r\n");
		sb.append("				height:90%; \r\n");
		sb.append(" 			width:99%; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		.ModalDialog {border: 1px #9F9F9F solid; background: #FFF; padding: 0px;margin: 10px auto; clear: both; position: absolute;  z-index: 10000;display:none;}\r\n");
		sb.append(" 		.header {border-bottom: 1px #DCDCDC solid; font-size: 12px; overflow: hidden; font-weight: normal; background: url('list_hd_bg.png') top left repeat-x;height:24px;}\r\n");
		sb.append(" 		.header .title {padding: 2px 3px;  float: left; font-weight: bold;line-height:20px;}\r\n");
		sb.append(" 		.header .operation {padding-top: 8px;padding-right:5px; float: right; cursor: pointer; text-decoration: none;}\r\n");
		sb.append(" 		.body {font-size: 9pt;margin: 0 !important; overflow-y: auto; padding: 10px 5px;}\r\n");
		sb.append(" 		.footer {padding: 0; text-align: center; font-size: 12px; margin-bottom: 10px;}\r\n");
		sb.append(" 	</style> \r\n");
		return sb.toString();
	}
	
	public static String getScriptStr(String topcompanyname,String yytName){
		StringBuffer sb = new StringBuffer();
		sb.append(" 	<script>\r\n ");
		sb.append("    		var isSetXieyi=false; \r\n");
		sb.append(" 		var currZancunFile=-1;\r\n ");
		sb.append(" 		var currZancunFilePath;\r\n ");
		sb.append(" 		var username=\"guest\";\r\n ");
		sb.append(" 		var modelfolder=\""+modelfolder+"\";\r\n ");
		sb.append(" 		var userStatus=0;\r\n ");
		sb.append(" 		var savePath=\"d:/hoteltest/guest\";\r\n ");
		sb.append(" 		var topcompanyname=\"").append(topcompanyname).append("\";\r\n");
		sb.append(" 		var yytName=\"").append(yytName).append("\";\r\n");
		sb.append(" 		var currtemplateName;\r\n ");
		sb.append(" 		var currdispayName;\r\n ");
		sb.append(" 		var openZancun=0;\r\n ");
		sb.append(" 		var ocxReady=0;\r\n ");
		sb.append(" 		function onLoad(){\r\n ");
		sb.append(" 			var tempInfo=document.getElementById(\"templateInfo\").value;\r\n ");
		sb.append(" 			var temparr=eval(tempInfo);\r\n ");
		sb.append(" 			getParamFromURL();\r\n ");
		sb.append(" 			var tempDiv=document.getElementById(\"TemplateDiv\");\r\n");
		sb.append(" 			var s=\"\";\r\n");
		sb.append(" 			for(var i=0;i<temparr.length;i++){\r\n");
		sb.append(" 				s=s+'<div id=\"tempDiv_child\"+i style=\"margin-left:0px;float:left;\">'\r\n");
		sb.append(" 				s=s+'<div style=\"background-image:url(images/top_2_03.gif);width:37px;height:37px;float:left;\"></div>'\r\n");
		sb.append(" 				s=s+'<div onclick=showAIP(\"'+temparr[i].name+'\",\"'+temparr[i].display+'\") style=\"background-image:url(images/top_2_05.gif);height:37px;float:left;padding:9px;width:200px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;\">'\r\n");
		sb.append(" 				s=s+'<font style=\"font-size:18px;font-family:华文行楷;\">'+temparr[i].display+'</font>'\r\n");
		sb.append(" 				s=s+'</div>'\r\n");
		sb.append(" 				s=s+'</div>'\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 			tempDiv.innerHTML=s;\r\n");
//		sb.append(" 			var j=0; \r\n");
//		sb.append("   	 for(var i=0;i<temparr.length;i++){ \r\n");
//		sb.append("   	 j++; \r\n");
//		sb.append("  	 document.getElementById(\"tdtemplateMenucontent\").innerHTML=document.getElementById(\"tdtemplateMenucontent\").innerHTML+\"&nbsp;<input class='btn1_mouseout' onMouseOver=\\\"this.className='btn1_mouseover'\\\" onmouseout=\\\"this.className='btn1_mouseout'\\\" onmousedown=\\\"this.className='btn1_mousedown'\\\" onmouseup=\\\"this.className='btn1_mouseup'\\\"  type=button name=\"+temparr[i].name+\" value=\"+temparr[i].display+\" onclick=showAIP('\"+temparr[i].name+\"','\"+temparr[i].display+\"')>\"; \r\n");
//		sb.append("  	 if(j%4==0){ \r\n");
//		sb.append("  	 document.getElementById(\"tdtemplateMenucontent\").innerHTML=document.getElementById(\"tdtemplateMenucontent\").innerHTML+\"<br>\"; \r\n");
//		sb.append("  	 } \r\n");
//		sb.append("  	 } \r\n");
		sb.append(" 			ocxReady=ocxReady+1;\r\n ");
		sb.append(" 			if(ocxReady==2){				\r\n ");
		sb.append(" 				viewList();\r\n ");
		sb.append(" 			}\r\n ");
		sb.append(" 		}\r\n ");
		sb.append(" 		function getParamFromURL(){\r\n ");
		sb.append(" 			var url=window.location.href;\r\n ");
		sb.append(" 			var temp=url.split(\"?\");\r\n ");
		sb.append(" 			var params=temp[1].split(\"&\");\r\n ");
		sb.append(" 			username=params[0].split(\"=\")[1];\r\n ");
		sb.append(" 			userStatus=params[1].split(\"=\")[1];\r\n ");
		sb.append(" 			savePath=params[2].split(\"=\")[1];\r\n ");
		sb.append(" 			savePath=savePath.replace(/%20/g, \" \");\r\n ");
		sb.append(" 		}\r\n ");
		sb.append(" 		var isshowTemplateDiv=1;\r\n");
		sb.append(" 		function showTemplateDiv(){\r\n");
		sb.append(" 			if(isshowTemplateDiv==0){\r\n");
		sb.append(" 				document.getElementById(\"TemplateDiv\").style.display=\"block\";\r\n");
		//sb.append(" 				document.getElementById(\"TemplateButton\").value=\"隐藏模板\";\r\n");
		sb.append(" 				document.getElementById(\"TemplateButton\").src=\"images/002.gif\";\r\n");
		sb.append(" 				isshowTemplateDiv=1;\r\n");
		sb.append(" 			}else{\r\n");
		sb.append(" 				document.getElementById(\"TemplateDiv\").style.display=\"none\";\r\n");
		//sb.append(" 				document.getElementById(\"TemplateButton\").value=\"显示模板\";\r\n");
		sb.append(" 				document.getElementById(\"TemplateButton\").src=\"images/001.gif\";\r\n");
		sb.append(" 				isshowTemplateDiv=0;\r\n");
		sb.append(" 			}\r\n");
		sb.append(" 		}\r\n");
		sb.append(" 		function showAIP(templateName,dispayName){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			currtemplateName=templateName;\r\n ");
		sb.append(" 			currdispayName=dispayName;\r\n ");
		sb.append(" 			openZancun=0;\r\n ");
		sb.append("    			isSetXieyi=false; \r\n");
		sb.append(" //			if(!objAIP.IsSaved()){\r\n ");
		sb.append(" //				if(!window.confirm(\"文档被修改，是否丢弃\")){\r\n ");
		sb.append(" //					return;\r\n ");
		sb.append(" //				}\r\n ");
		sb.append(" //			}\r\n ");
		sb.append(" 			objAIP.LoadFile(savePath+\"/\"+modelfolder+\"/\"+templateName);\r\n ");
//		sb.append("				var myDate = new Date();\r\n ");
//		sb.append("				var code=\"\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+parseInt(100*Math.random());\r\n ");
//		sb.append("				objAIP.SetValue(\"code\",code);\r\n ");
//		sb.append("				var indate=\"\"+myDate.getFullYear()+\"年\"+(myDate.getMonth()+1)+\"月\"+myDate.getDate()+\"日\";\r\n ");
//		sb.append("				objAIP.SetValue(\"indate\",indate);\r\n ");
		sb.append("  			var myDate = new Date();  \r\n");
		sb.append("  			var shouliNo=\"\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+parseInt(1000*Math.random());  \r\n");
		sb.append("  			objAIP.SetValue(\"shouliNo\",\"\");  \r\n");
		sb.append("  			objAIP.SetValue(\"shouliNo\",shouliNo);  \r\n");
		sb.append("  			objAIP.SetValue(\"title\",\"\");  \r\n");
		sb.append("  			objAIP.SetValue(\"title\",\"中国联合网络通信有限公司\"+topcompanyname+\"综合业务受理单\");  \r\n");
		sb.append("  			objAIP.SetValue(\"shouliNo\",\":PROP::LABEL:3\");  \r\n");
		sb.append("  			objAIP.SetValue(\"title\",\":PROP::LABEL:3\");  \r\n");
		sb.append(" 			document.getElementById(\"message\").innerText=\"当前使用模板：\"+currdispayName;\r\n");
		sb.append(" 		}\r\n ");
		sb.append(" 		function viewList(){\r\n ");
		sb.append(" 		 	var table=document.getElementById(\"zancunTable\");\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			var filelist=objAIP.GetFileListUnderDir(savePath+\"local/\");\r\n ");
		sb.append(" 			//var filelist=\"d:/hoteltest/guest/local/test.aip;\";\r\n ");
		sb.append(" 			var rowNum=table.rows.length;\r\n ");
		sb.append(" 		    for (i=0;i<rowNum;i++)\r\n ");
		sb.append(" 		    {\r\n ");
		sb.append(" 		        table.deleteRow(i);\r\n ");
		sb.append(" 		        rowNum=rowNum-1;\r\n ");
		sb.append(" 		        i=i-1;\r\n ");
		sb.append(" 		    }\r\n ");
		sb.append(" 			var fileArr=filelist.split(\";\");\r\n ");
		sb.append(" 			for(var i=0;i<fileArr.length-1;i++){\r\n ");
		sb.append(" 				var temp=fileArr[i].split(\"/\");\r\n ");
		sb.append(" 				var fileTemp=temp[temp.length-1];\r\n ");
		sb.append(" 				var fileTemp2=fileTemp.split(\"\\\\\");\r\n ");
		sb.append(" 				var temp2=fileTemp2[1].split(\".\");\r\n ");
		sb.append(" 				var fileName=temp2[0];\r\n ");
		sb.append(" 				var newRow=table.insertRow();\r\n ");
		sb.append(" 				var newCell=newRow.insertCell();\r\n ");
		sb.append(" 				var filepath=fileArr[i].replace(\"/\\\\\",\"/\");\r\n ");
		sb.append(" 			    filepath=filepath.replace(/ /g, \"%20\");\r\n ");
		sb.append(" 				newCell.innerHTML=\"<a href='#' onclick=editAIP(this,'\"+filepath+\"')>\"+fileName+\"</a>\";\r\n ");//没有删除按钮
//		sb.append(" 				newCell.innerHTML=\"<a href='#' onclick=editAIP(this,'\"+filepath+\"')>\"+fileName+\"</a>\"+\"<a href='#' onclick=deleteAIP(this,'\"+filepath+\"')>×</a>\";\r\n ");//有删除按钮
		sb.append(" 			}\r\n ");
		sb.append(" 		}\r\n ");
		sb.append(" 		function editAIP(obj,filePath){\r\n ");
		sb.append(" 			currZancunFile=obj.parentNode.parentNode.rowIndex;\r\n ");
		sb.append(" 			openZancun=1;\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			var templateName=document.getElementById(templateName);\r\n ");
		sb.append(" 			if(!objAIP.IsSaved()){\r\n ");
		sb.append(" 				if(!window.confirm(\"文档被修改，是否丢弃\")){\r\n ");
		sb.append(" 					return;\r\n ");
		sb.append(" 				}\r\n ");
		sb.append(" 			}\r\n ");
		sb.append(" 			objAIP.CloseDoc(0);\r\n ");
		sb.append(" 			filePath=filePath.replace(/%20/g, \" \");\r\n ");
		sb.append(" 			objAIP.LoadFile(filePath);\r\n ");
		sb.append(" 			currZancunFilePath=filePath;\r\n ");
		sb.append(" 		}\r\n ");
		sb.append(" 		function deleteAIP(obj,filePath){\r\n ");
		sb.append(" 			currZancunFile=obj.parentNode.parentNode.rowIndex;\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			if(window.confirm(\"确定要删除此暂存文档吗?\")){\r\n ");
		sb.append(" 				objAIP.DeleteLocalFile(deletepath);\r\n ");
		sb.append(" 				if(currZancunFilePath==deletepath){\r\n ");
		sb.append(" 					objAIP.CloseDoc(0);\r\n ");
		sb.append(" 					openZancun=0;\r\n ");
		sb.append(" 				}\r\n ");
		sb.append(" 			}\r\n ");
		sb.append(" 			viewList();\r\n ");
		sb.append(" 		}\r\n ");
		sb.append(" 		function handWrite(){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append("    			var doctype = objAIP.CurrDocType;       \r\n ");
		sb.append("  			if(doctype==31){   \r\n ");
		sb.append("  				alert(\"文档已盖章，不能再签字！\");   \r\n ");
		sb.append("  				return false;   \r\n ");
		sb.append("  			}   \r\n ");
		sb.append(" 			objAIP.Login(username,2, 65535,\"\",\"\");\r\n ");
		sb.append("  			objAIP.SetValue(\"LABEL_ALLNOTES_STATUS\",\"3\");//设置所有节点不可选 \r\n ");
//		sb.append("  			objAIP.SetValue(\"Page1.NameWriteArea\",\":PROP::LABEL:0\"); \r\n ");
//		sb.append("  			objAIP.SetValue(\"Page1.PhoneWriteArea\",\":PROP::LABEL:0\"); \r\n ");
		sb.append(" 			objAIP.ShowFullScreen = 1;\r\n ");
		sb.append(" 			objAIP.CurrAction=264;\r\n ");
		sb.append(" 		}\r\n ");
		
		//加入身份证功能的新版本新增的方法 开始
//		sb.append("     function addIdCardImg(){   \r\n ");
//		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");   \r\n ");
//		sb.append("  			var doctype = objAIP.CurrDocType;     \r\n ");
//		sb.append("  			if(doctype==31){   \r\n ");
//		sb.append("  				alert(\"文档已盖章，不能修改！\");   \r\n ");
//		sb.append("  				return false;   \r\n ");
//		sb.append("  			}   \r\n ");
//		sb.append("  			var vRet = objAIP.Login(username,2, 65535,\"\",\"\");   \r\n ");
//		sb.append("  			var idcardtemplate=document.getElementById(\"身份证图片页\");   \r\n ");
//		sb.append("  			var data = idcardtemplate.value;   \r\n ");
//		sb.append("  			var pagenum = objAIP.PageCount;   \r\n ");
//		sb.append("  			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);   \r\n ");
//		sb.append("  			if(m==1){   \r\n ");
//		sb.append("    				pagenum = objAIP.PageCount; \r\n ");
//		sb.append("    				var deletepagenum =  pagenum -1;  \r\n ");
//		sb.append("  				var openret=CardReader_CMCC.MutiIdCardOpenDevice(1000);//打开设备   \r\n ");
//		sb.append("					if(openret!=0){   \r\n ");
//		sb.append("						if(window.confirm(\"打开设备失败,是否显示演示效果?\")){\r\n ");
//		sb.append(" 									objAIP.SetValue(\"Page\"+pagenum+\".idcardpicture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");   \r\n ");
//		sb.append("   			     			objAIP.CurrPage(deletepagenum);//跳转到第二页 \r\n ");
//		sb.append("   			     			return false;  \r\n ");
//		sb.append(" 							}else{\r\n ");
//		sb.append(" 								 objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append("			 						alert(\"打开设备失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append("			 						return false; \r\n ");
//		sb.append(" 							}  \r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("  				var statusret=CardReader_CMCC.MutiIdCardGetDeviceStatus();//获取设备状态   \r\n ");
//		sb.append("					if(statusret!=0){   \r\n ");
//		sb.append("  			        objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append("						alert(\"设备状态异常，异常信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append("						return false;   \r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("					   \r\n ");
//		sb.append("					var photoret=CardReader_CMCC.MutiIdCardPhotograph('C:/hotel_idcardinfo.jpg',1);   \r\n ");
//		sb.append("					if(photoret!=0){   \r\n ");
//		sb.append("  			        objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append("						alert(\"拍照出错，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append("						return false;   \r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("					CardReader_CMCC.MutiIdCardCloseDevice();//关闭设备   \r\n ");
//		sb.append("					objAIP.SetValue(\"Page\"+pagenum+\".idcardpicture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");   \r\n ");
//		sb.append("					objAIP.DeleteLocalFile(\"C:/hotel_idcardinfo.jpg\"); \r\n ");
//		sb.append("  			     objAIP.CurrPage(deletepagenum);//跳转到第二页   \r\n ");
//		sb.append("  			}else{   \r\n ");
//		sb.append("  				alert(\"插入页失败!\");   \r\n ");
//		sb.append("  				return false;   \r\n ");
//		sb.append("  			}   \r\n ");
//		sb.append("  		}   \r\n ");
//		sb.append("  		   \r\n ");
//		sb.append("  		   \r\n ");
//		
//		sb.append("  		//FT2000多功能身份采集仪   \r\n ");
//		sb.append("  		function addIdCardInfo(){   \r\n ");
//		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");   \r\n ");
//		sb.append("  			var doctype = objAIP.CurrDocType;     \r\n ");
//		sb.append("  			if(doctype==31){   \r\n ");
//		sb.append("  				alert(\"文档已盖章，不能修改！\");   \r\n ");
//		sb.append("  				return false;   \r\n ");
//		sb.append("  			}   \r\n ");
//		sb.append("  			var vRet = objAIP.Login(username,2, 65535,\"\",\"\");   \r\n ");
//		sb.append("  			var idcardtemplate=document.getElementById(\"身份证信息页\");   \r\n ");
//		sb.append("  			var data = idcardtemplate.value;   \r\n ");
//		sb.append("  			var pagenum = objAIP.PageCount;   \r\n ");
//		sb.append("  			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);   \r\n ");
//		sb.append("  			if(m==1){   \r\n ");
//		sb.append("    				pagenum = objAIP.PageCount; \r\n ");
//		sb.append("    				var deletepagenum =  pagenum -1;  \r\n ");
//		sb.append("  				var openret=CardReader_CMCC.MutiIdCardOpenDevice(1000);//打开设备   \r\n ");
//		sb.append("					if(openret!=0){   \r\n ");
//		sb.append("						if(window.confirm(\"打开设备失败,是否显示演示效果?\")){\r\n ");
//		sb.append(" 							objAIP.SetValue(\"Page\"+pagenum+\".name\",\"张三\");  //姓名   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".sex\",\"男\"); //性别   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".people\",\"汉\"); //名族     \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".nian\",\"1980\"); //出生年月   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".yue\",\"01\"); //出生年月   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".ri\",\"01\"); //出生年月   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".address\",\"广东省深圳市\"); //住址   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",\"110110111111111111\"); //身份证号   \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",\"广东省深圳市公安局\");//签发机关  \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",\"2012.01.01\"+\"-\"+\"2013.01.01\");//有效期限  \r\n ");
//		sb.append("				  				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:C:/hotel_touxiang.jpg\");//头像图片  \r\n ");
//		sb.append("				 				objAIP.CurrPage(deletepagenum);//跳转到最后一页  \r\n ");
//		sb.append("				 				return false; \r\n ");
//		sb.append(" 						}else{\r\n ");
//		sb.append(" 							objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append(" 							alert(\"打开设备失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append(" 							return false; \r\n ");
//		sb.append(" 						}\r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("  				var statusret=CardReader_CMCC.MutiIdCardGetDeviceStatus();//获取设备状态   \r\n ");
//		sb.append("					if(statusret!=0){   \r\n ");
//		sb.append("  			        objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append("						alert(\"设备状态异常，异常信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append("						return false;   \r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("					var imgret=CardReader_CMCC.MutiIdCardGetImageMsg(11,'C:/hotel_idcardinfo.jpg');//拍照识别电子影印件信息   \r\n ");
//		sb.append("					if(imgret!=0){   \r\n ");
//		sb.append("  			        objAIP.DeletePage(deletepagenum);   \r\n ");
//		sb.append("						alert(\"拍照识别出错，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());   \r\n ");
//		sb.append("						return false;   \r\n ");
//		sb.append("					}   \r\n ");
//		sb.append("                 objAIP.SetValue(\"Page\"+pagenum+\".name\",CardReader_CMCC.MutiIdCardName);  //姓名   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".sex\",CardReader_CMCC.MutiIdCardSex); //性别   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".people\",CardReader_CMCC.MutiIdCardPeople); //名族   \r\n ");
//		sb.append(" 				var datestr = CardReader_CMCC.MutiIdCardBirthday;   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".nian\",getDateStr(datestr,\"nian\")); //出生年月   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".yue\",getDateStr(datestr,\"yue\")); //出生年月   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".ri\",getDateStr(datestr,\"ri\")); //出生年月   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".address\",CardReader_CMCC.MutiIdCardAddress); //住址   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",CardReader_CMCC.MutiIdCardNumber); //身份证号   \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",CardReader_CMCC.MutiIdCardOrgans);//签发机关  \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",CardReader_CMCC.MutiIdCardSigndate+\"-\"+CardReader_CMCC.MutiIdCardValidterm);//有效期限  \r\n ");
//		sb.append(" 				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:C:/hotel_idcardinfo.jpg\");//头像图片   \r\n ");
//		sb.append("            objAIP.SetValue(\"Page1.guestname1\",\"\");  //姓名  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.guestname1\",CardReader_CMCC.MutiIdCardName);  //姓名  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.sex\",\"\");  //性别   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.sex\",CardReader_CMCC.MutiIdCardSex);  //性别   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.cardNO1\",\"\");  //身份证号     \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.cardNO1\",CardReader_CMCC.MutiIdCardNumber);  //身份证号      \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.birth\",\"\");  //出生年月日  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.birth\",getDateStr(datestr,\"nian\")+\"年\"+getDateStr(datestr,\"yue\")+\"月\"+getDateStr(datestr,\"ri\")+\"日\");  //出生年月日  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.address\",\"\"); //住址   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.address\",CardReader_CMCC.MutiIdCardAddress); //住址 \r\n ");
//		sb.append("					CardReader_CMCC.MutiIdCardCloseDevice();//关闭设备   \r\n ");
//		sb.append("					objAIP.DeleteLocalFile(\"C:/hotel_idcardinfo.jpg\"); \r\n ");
//		sb.append("  			    objAIP.CurrPage(deletepagenum);//跳转到最后一页   \r\n ");
//		sb.append("  			}else{   \r\n ");
//		sb.append("  				alert(\"插入页失败!\");   \r\n ");
//		sb.append("  				return false;   \r\n ");
//		sb.append("  			}   \r\n ");
//		sb.append("  		}   \r\n ");
		
//		sb.append("        //普天二代身份证阅读器  \r\n ");
//		sb.append("    		function addIdCardInfo(){     \r\n ");
//		sb.append("    			var objAIP=document.getElementById(\"HWPostil1\");     \r\n ");
//		sb.append("    			var doctype = objAIP.CurrDocType;       \r\n ");
//		sb.append("    			if(doctype==31){     \r\n ");
//		sb.append("    				alert(\"文档已盖章，不能修改！\");     \r\n ");
//		sb.append("    				return false;     \r\n ");
//		sb.append("    			}     \r\n ");
//		sb.append("    			var vRet = objAIP.Login(username,2, 65535,\"\",\"\");     \r\n ");
//		sb.append("    			var idcardtemplate=document.getElementById(\"身份证信息页\");     \r\n ");
//		sb.append("    			var data = idcardtemplate.value;   \r\n ");
//		sb.append("    			var pagenum = objAIP.PageCount;   \r\n ");
//		sb.append("    			var m = objAIP.MergeFile(pagenum,\"STRDATA:\"+data);    \r\n ");
//		sb.append("    			if(m==1){\r\n ");
//		sb.append("    				pagenum = objAIP.PageCount; \r\n ");
//		sb.append("    				var deletepagenum =  pagenum -1;  \r\n ");
//		sb.append("    				var openret=CardReader_CMCC.IdCardOpenDevice(1000);//打开设备     \r\n ");
//		sb.append("  					if(openret!=0){     \r\n ");
//		sb.append("    			        objAIP.DeletePage(deletepagenum);     \r\n ");
//		sb.append("  						alert(\"打开设备失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());     \r\n ");
//		sb.append("  						return false;     \r\n ");
//		sb.append("  					}     \r\n ");
//		sb.append("    				var statusret=CardReader_CMCC.IdCardGetDeviceStatus();//获取设备状态    \r\n ");
//		sb.append("  					if(statusret!=131000){     \r\n ");
//		sb.append("    			        objAIP.DeletePage(deletepagenum);     \r\n ");
//		sb.append("  						alert(\"设备状态异常，异常信息为：\"+CardReader_CMCC.GetLastErrMsg());     \r\n ");
//		sb.append("  						return false;     \r\n ");
//		sb.append("  					}     \r\n ");
//		sb.append("  					var readret=CardReader_CMCC.IdCardReadCard();//读卡操作  \r\n ");
//		sb.append("  					if(readret!=131001){     \r\n ");
//		sb.append("    			        objAIP.DeletePage(deletepagenum);     \r\n ");
//		sb.append("  						alert(\"读卡失败，错误信息为：\"+CardReader_CMCC.GetLastErrMsg());     \r\n ");
//		sb.append("  						return false;     \r\n ");
//		sb.append("  					}   		  \r\n ");
//		sb.append("  					CardReader_CMCC.IdCardGetCardInfo(0);  \r\n ");
//		sb.append("	 					var name = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(1);  \r\n ");
//		sb.append("	 					var sex = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(2);  \r\n ");
//		sb.append("	 					var people = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(3);  \r\n ");
//		sb.append("	 					var riqi = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(4);  \r\n ");
//		sb.append("	 					var address = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(5);  \r\n ");
//		sb.append("	 					var no = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(6);  \r\n ");
//		sb.append("	 					var qianfa = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(7);  \r\n ");
//		sb.append("	 					var datebegin = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(8);  \r\n ");
//		sb.append("	 					var dateend = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	 					CardReader_CMCC.IdCardGetCardInfo(10);  \r\n ");
//		sb.append("	 					var picturePath = CardReader_CMCC.IDCardGetLastValue();  \r\n ");
//		sb.append("	                objAIP.SetValue(\"Page\"+pagenum+\".name\",name);  //姓名     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".sex\",sex); //性别     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".people\",people); //名族     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".nian\",getDateStr(riqi,\"nian\")); //出生年月     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".yue\",getDateStr(riqi,\"yue\")); //出生年月     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".ri\",getDateStr(riqi,\"ri\")); //出生年月     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".address\",address); //住址     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".idcardno\",no); //身份证号     \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".qianfa\",qianfa);//签发机关  \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".youxiaoqi\",DateJiaDian(datebegin)+\"-\"+DateJiaDian(dateend));//有效期限  \r\n ");
//		sb.append("	   				objAIP.SetValue(\"Page\"+pagenum+\".picture\",\"BMPFILE:\"+picturePath);//头像图片     \r\n ");
//		sb.append("            objAIP.SetValue(\"Page1.guestname1\",\"\");  //姓名  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.guestname1\",name);  //姓名  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.sex\",\"\");  //性别   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.sex\",sex);  //性别   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.cardNO1\",\"\");  //身份证号     \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.cardNO1\",no);  //身份证号      \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.birth\",\"\");  //出生年月日  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.birth\",getDateStr(riqi,\"nian\")+\"年\"+getDateStr(riqi,\"yue\")+\"月\"+getDateStr(riqi,\"ri\")+\"日\");  //出生年月日  \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.address\",\"\"); //住址   \r\n ");
//		sb.append(" 	   				objAIP.SetValue(\"Page1.address\",address); //住址 \r\n ");
//		sb.append("	  			  CardReader_CMCC.IdCardCloseDevice();//关闭设备 \r\n ");
//		sb.append("	  			  objAIP.DeleteLocalFile(picturePath);     \r\n ");
//		sb.append("	    			objAIP.CurrPage(deletepagenum);//跳转到最后一页     \r\n ");
//		sb.append("    			}else{     \r\n ");
//		sb.append("    				alert(\"插入页失败!\");     \r\n ");
//		sb.append("    				return false;     \r\n ");
//		sb.append("    			}     \r\n ");
//		sb.append("    		}\r\n ");
		
//		sb.append("   		function getDateStr(str,type){ \r\n ");
//		sb.append("    			if(str==\"长期\"){ \r\n ");
//		sb.append("    				return str;  \r\n ");
//		sb.append("    			}else if(str.length!=8){ \r\n ");
//		sb.append("    				alert(\"获取到的日期有误：\"+str);	 \r\n ");
//		sb.append("    				return false; \r\n ");
//		sb.append("    			} \r\n ");
//		sb.append("   			if(type==\"nian\"){ \r\n ");
//		sb.append("   				var ret = str.substring(0,4); \r\n ");
//		sb.append("   				return ret; \r\n ");
//		sb.append("   			}else if(type==\"yue\"){ \r\n ");
//		sb.append("   				var ret = str.substring(4,6); \r\n ");
//		sb.append("   				if(ret<10){ \r\n ");
//		sb.append("   					return ret.substring(1,2); \r\n ");
//		sb.append("   				}else{ \r\n ");
//		sb.append("   					return ret; \r\n ");
//		sb.append("   				} \r\n ");
//		sb.append("   			}else if(type==\"ri\"){ \r\n ");
//		sb.append("   				var ret = str.substring(6,8); \r\n ");
//		sb.append("   				if(ret<10){ \r\n ");
//		sb.append("   					return ret.substring(1,2); \r\n ");
//		sb.append("   				}else{ \r\n ");
//		sb.append("   					return ret; \r\n ");
//		sb.append("   				} \r\n ");
//		sb.append("   			} \r\n ");
//		sb.append("   		} \r\n ");
//		sb.append("    	function DateJiaDian(str){  \r\n ");
//		sb.append("    				if(str==\"长期\"){ \r\n ");
//		sb.append("    					return str;  \r\n ");
//		sb.append("    				}else if(str.length!=8){ \r\n ");
//		sb.append("    					alert(\"获取到的日期有误：\"+str);	 \r\n ");
//		sb.append("    					return false; \r\n ");
//		sb.append("    				} \r\n ");
//		sb.append("    				var nian = str.substring(0,4);  \r\n ");
//		sb.append("    				var yue = str.substring(4,6);  \r\n ");
//		sb.append("    				var ri = str.substring(6,8);  \r\n ");
//		sb.append("    				return nian+\".\"+yue+\".\"+ri; \r\n ");
//		sb.append("    	} \r\n ");

		//加入身份证功能的新版本新增的方法 结束
		
		//加入盖章功能的新版本新增的方法 开始
//		sb.append("  		function addPrivateSeal(){       \r\n ");
//		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");       \r\n ");
//		sb.append("  			var l = objAIP.Login(\"\",3, 65535,\"\",\"\");       \r\n ");
//		sb.append("  			if(l!=0){       \r\n ");
//		sb.append("  				if(l==-200){       \r\n ");
//		sb.append("  					alert(\"请插入key！\");       \r\n ");
//		sb.append("  					return false;       \r\n ");
//		sb.append("  				}else{       \r\n ");
//		sb.append("  					alert(\"盖章登录失败！返回值为：\"+l);       \r\n ");
//		sb.append("  					return false;       \r\n ");
//		sb.append("  				}       \r\n ");
//		sb.append("  			}       \r\n ");
//		sb.append("  			var doctype = objAIP.CurrDocType;       \r\n ");
//		sb.append("  			if(doctype!=31){       \r\n ");
//		sb.append("  				if(openZancun==1){       \r\n ");
//		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
//		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
//		sb.append("                     }       \r\n ");
//		sb.append("	  				var filepath=objAIP.PathName;       \r\n ");
//		sb.append("  				 var deletepath=filepath;     \r\n ");
//		sb.append("	  				var temp=filepath.split(\".\");       \r\n ");
//		sb.append("	  				filepath=temp[0]+\".pdf\";       \r\n ");
//		sb.append("	  				var currfileName =  temp[0].substring(temp[0].lastIndexOf(\"/\")+1,temp[0].length);       \r\n ");
//		sb.append("	  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
//		sb.append("	  				var myDate = new Date();       \r\n ");
//		sb.append("            var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
//		sb.append("            objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
//		sb.append(" 						objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
//		sb.append("	  				var res=objAIP.SaveTo(filepath,\"pdf\",0);       \r\n ");
//		sb.append("  				 if(res!=0){     \r\n ");
//		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
//		sb.append("  				 }else{     \r\n ");
//		sb.append("  				     alert(\"盖个人章保存出错！\");    \r\n ");
//		sb.append("  				     return false;     \r\n ");
//		sb.append("  				 }     \r\n ");
//		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
//		sb.append("	  				objAIP.LoadFile(filepath);       \r\n ");
//		sb.append("  				}else{       \r\n ");
//		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
//		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
//		sb.append("             }       \r\n ");
//		sb.append("  					var myDate = new Date();       \r\n ");
//		sb.append("  					var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
//		sb.append("  					var savefilePath=savePath+\"local/\"+currfileName+\".pdf\";       \r\n ");
//		sb.append("  					var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
//		sb.append("            var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
//		sb.append("            objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
//		sb.append(" 						objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
//		sb.append("  					var res=objAIP.SaveTo(savefilePath,\"pdf\",0);       \r\n ");
//		sb.append("  				    if(res!=0){     \r\n ");
//		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
//		sb.append("  				    }else{     \r\n ");
//		sb.append("  				      alert(\"盖个人章保存出错！\");    \r\n ");
//		sb.append("  				      return false;     \r\n ");
//		sb.append("  				    }     \r\n ");
//		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
//		sb.append("  					objAIP.LoadFile(savefilePath);       \r\n ");
//		sb.append("  				}       \r\n ");
//		sb.append("  			}       \r\n ");
//		sb.append("  			var s1=objAIP.SetValue(\"SET_SEAL_TYPE_FORADD\",\"2\");//个人章       \r\n ");
//		sb.append("  			objAIP.CurrAction=2568;       \r\n ");
//		sb.append("  		}       \r\n ");
//		sb.append("  		       \r\n ");
//		sb.append("  		function addPublicSeal(){       \r\n ");
//		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");       \r\n ");
//		sb.append("  			var l = objAIP.Login(\"\",3, 65535,\"\",\"\");       \r\n ");
//		sb.append("  			if(l!=0){       \r\n ");
//		sb.append("  				if(l==-200){       \r\n ");
//		sb.append("  					alert(\"请插入key！\");       \r\n ");
//		sb.append("  					return false;       \r\n ");
//		sb.append("  				}else{       \r\n ");
//		sb.append("  					alert(\"盖章登录失败！返回值为：\"+l);       \r\n ");
//		sb.append("  					return false;       \r\n ");
//		sb.append("  				}       \r\n ");
//		sb.append("  			}       \r\n ");
//		sb.append("  			var doctype = objAIP.CurrDocType;       \r\n ");
//		sb.append("  			if(doctype!=31){       \r\n ");
//		sb.append("  				if(openZancun==1){       \r\n ");
//		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
//		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
//		sb.append("             }       \r\n ");
//		sb.append("	  				var filepath=objAIP.PathName;       \r\n ");
//		sb.append("  				 var deletepath=filepath;     \r\n ");
//		sb.append("	  				var temp=filepath.split(\".\");       \r\n ");
//		sb.append("	  				filepath=temp[0]+\".pdf\";       \r\n ");
//		sb.append("	  				var currfileName =  temp[0].substring(temp[0].lastIndexOf(\"/\")+1,temp[0].length);       \r\n ");
//		sb.append("	  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
//		sb.append("	  				var myDate = new Date();       \r\n ");
//		sb.append("            var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
//		sb.append("            objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
//		sb.append(" 						objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
//		sb.append("	  				var res=objAIP.SaveTo(filepath,\"pdf\",0);       \r\n ");
//		sb.append("  				 if(res!=0){     \r\n ");
//		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
//		sb.append("  				 }else{     \r\n ");
//		sb.append("  				     alert(\"盖公章保存出错！\");    \r\n ");
//		sb.append("  				     return false;     \r\n ");
//		sb.append("  				 }     \r\n ");
//		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
//		sb.append("	  				objAIP.LoadFile(filepath);       \r\n ");
//		sb.append("  				}else{       \r\n ");
//		sb.append("  					if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){               \r\n ");
//		sb.append(" 			   				objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);       \r\n ");
//		sb.append("             }       \r\n ");
//		sb.append("  					var myDate = new Date();       \r\n ");
//		sb.append("  					var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
//		sb.append("  					var savefilePath=savePath+\"local/\"+currfileName+\".pdf\";       \r\n ");
//		sb.append("  					var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
//		sb.append("            var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();       \r\n ");
//		sb.append("            objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);       \r\n ");
//		sb.append(" 						objAIP.ExportEditNodeValue(\"\",infpath,2);       \r\n ");
//		sb.append("  					var res=objAIP.SaveTo(savefilePath,\"pdf\",0);       \r\n ");
//		sb.append("  				    if(res!=0){     \r\n ");
//		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
//		sb.append("  				    }else{     \r\n ");
//		sb.append("  				       alert(\"盖公章保存出错！\");    \r\n ");
//		sb.append("  				       return false;     \r\n ");
//		sb.append("  				    }     \r\n ");
//		sb.append("  				   objAIP.CloseDoc(0);     \r\n ");
//		sb.append("  					objAIP.LoadFile(savefilePath);       \r\n ");
//		sb.append("  				}       \r\n ");
//		sb.append("  			}       \r\n ");
//		sb.append("  			var s1=objAIP.SetValue(\"SET_SEAL_TYPE_FORADD\",\"1\");//公章       \r\n ");
//		sb.append("  			objAIP.CurrAction=2568;       \r\n ");
//		sb.append("  		}       \r\n ");
		//加入盖章功能的新版本新增的方法 结束
		
		//老版本的暂存和上传方法 开始
//		sb.append(" 		function saveTemp(){\r\n ");
//		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
//		sb.append(" 			var filepath=objAIP.PathName;\r\n ");
//		sb.append(" 			if(openZancun==1){\r\n ");
//		sb.append(" 				objAIP.SaveTo(filepath,\"aip\",0);\r\n ");
//		sb.append(" 			}else{\r\n ");
//		sb.append(" 				var myDate = new Date();\r\n ");
//		sb.append(" 				var savefilePath=savePath+\"local/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".aip\";\r\n ");
//		sb.append(" 			    objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);\r\n");
//		sb.append(" 				objAIP.SaveTo(savefilePath,\"aip\",0);\r\n ");
//		sb.append(" 			}\r\n ");
//		sb.append(" 			openZancun=1;\r\n ");
//		sb.append(" 			viewList();\r\n ");
//		sb.append(" 		}\r\n ");
//		sb.append(" 		function saveUpload(){\r\n ");
//		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
//		sb.append(" 			var filepath=objAIP.PathName;\r\n ");
//		sb.append("             if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){        \r\n");
//		sb.append(" 			   objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);\r\n");
//		sb.append("             }\r\n");
//		sb.append(" 			if(openZancun==1){\r\n ");
//		sb.append(" 				var deletepath=filepath;\r\n ");
//		sb.append(" 				filepath=filepath.replace(\"local\",\"remote\");\r\n ");
//		sb.append(" 				var temp=filepath.split(\".\");\r\n ");
//		sb.append(" 				filepath=temp[0]+\".pdf\";\r\n ");
//		sb.append(" 				var infpath=temp[0]+\".inf\";\r\n ");
//		sb.append("                 var myDate = new Date();\r\n");
//		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
//		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,2);\r\n ");
//		sb.append(" 				var res=objAIP.SaveTo(filepath,\"pdf\",1);\r\n ");
//		sb.append(" 				if(res!=0){\r\n ");
//		sb.append(" 					objAIP.DeleteLocalFile(deletepath);\r\n ");
//		sb.append(" 				}\r\n ");
//		sb.append(" 				var table=document.getElementById(\"zancunTable\");\r\n ");
//		sb.append(" 				table.deleteRow(currZancunFile);\r\n ");
//		sb.append(" 			}else{\r\n ");
//		sb.append(" 				var myDate = new Date();\r\n ");
//		sb.append(" 				var savefilePath=savePath+\"remote/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".pdf\";\r\n ");
//		sb.append(" 				var infpath=savePath+\"remote/\"+currdispayName+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".inf\";\r\n ");
//		sb.append("                 var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();\r\n");
//		sb.append("                 objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);\r\n");
//		sb.append(" 				objAIP.ExportEditNodeValue(\"\",infpath,2);\r\n ");
//		sb.append(" 				objAIP.SaveTo(savefilePath,\"pdf\",1);\r\n ");
//		sb.append(" 			}\r\n ");
//		sb.append(" 			objAIP.CloseDoc(0);\r\n ");
//		sb.append(" 		}\r\n ");
		//老版本的暂存和上传方法 结束
		
		
		//加入盖章功能的新版本的暂存和上传方法 开始
		sb.append("  		function saveTemp(){     \r\n ");
		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");     \r\n ");
		sb.append("  			var filepath=objAIP.PathName;     \r\n ");
		sb.append("  			var doctype = objAIP.CurrDocType;     \r\n ");
		sb.append("  			if(doctype==31){     \r\n ");
		sb.append("  				alert(\"当前文档已盖章，不能暂存！\");     \r\n ");
		sb.append("  				return false;     \r\n ");
		sb.append("  			}     \r\n ");
		sb.append("  			if(openZancun==1){     \r\n ");
		sb.append("  				objAIP.SaveTo(filepath,\"aip\",0);     \r\n ");
		sb.append("  			}else{     \r\n ");
		sb.append("  				var myDate = new Date();     \r\n ");
		sb.append("  				var savefilePath=savePath+\"local/\"+currdispayName+\"_\"+username+\"_\"+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds()+\".aip\";     \r\n ");
		sb.append("  			  objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);     \r\n ");
		sb.append(" 				  objAIP.SaveTo(savefilePath,\"aip\",0);     \r\n ");
		sb.append("  			}     \r\n ");
		sb.append("  			openZancun=1;     \r\n ");
		sb.append("  			viewList();     \r\n ");
		sb.append("  		}     \r\n ");
		sb.append("  		function saveUpload(){     \r\n ");
		sb.append("  			var objAIP=document.getElementById(\"HWPostil1\");     \r\n ");
		sb.append("  			var doctype = objAIP.CurrDocType;     \r\n ");
		sb.append("  			var filepath=objAIP.PathName;     \r\n ");
		sb.append("  			if(doctype==31){     \r\n ");
		sb.append("  				 var deletepath=filepath;     \r\n ");
		sb.append("  				 filepath=filepath.replace(\"local\",\"remote\");     \r\n ");
		sb.append("  				 var res=objAIP.SaveTo(filepath,\"pdf\",0);     \r\n ");
		sb.append("  				 if(res!=0){     \r\n ");
		sb.append("  						objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				 }else{     \r\n ");
		sb.append("  				     alert(\"上传保存出错！\");    \r\n ");
		sb.append("  				     return false;     \r\n ");
		sb.append("  				 }     \r\n ");
		sb.append("  				 objAIP.CloseDoc(0);     \r\n ");
		sb.append(" 				 if(openZancun==1){     \r\n ");
		sb.append("  				    var table=document.getElementById(\"zancunTable\");     \r\n ");
		sb.append("  				    table.deleteRow(currZancunFile);     \r\n ");
		sb.append("  			      }   \r\n ");
		sb.append("  				 return false;     \r\n ");
		sb.append("  			}     \r\n ");
		sb.append("        if(objAIP.DocProperty(\"DJ_TEMP_ID\")==\"\"){             \r\n ");
		sb.append(" 			   	objAIP.AddDocProperty(\"DJ_TEMP_ID\",currtemplateName);     \r\n ");
		sb.append("        }     \r\n ");
		sb.append(" 				if(openZancun==1){     \r\n ");
		sb.append("  				var deletepath=filepath;     \r\n ");
		sb.append("  				filepath=filepath.replace(\"local\",\"remote\");     \r\n ");
//		sb.append("  				var temp=filepath.split(\".\");     \r\n ");
//		sb.append("  				filepath=temp[0]+\".pdf\";     \r\n ");
//		sb.append("  				var infpath=temp[0]+\".inf\";     \r\n ");
		sb.append("  				filepath=filepath.replace(\".aip\",\".pdf\");        \r\n ");
		sb.append("  				var infpath=filepath.replace(\".aip\",\".inf\");      \r\n ");
		sb.append("          var myDate = new Date();     \r\n ");
		sb.append("          var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();     \r\n ");
		sb.append("          objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);     \r\n ");
		sb.append(" 				  objAIP.ExportEditNodeValue(\"\",infpath,2);     \r\n ");
		sb.append("  				var res=objAIP.SaveTo(filepath,\"pdf\",0);     \r\n ");
		sb.append("  				if(res!=0){     \r\n ");
		sb.append("  					objAIP.DeleteLocalFile(deletepath);     \r\n ");
		sb.append("  				 }else{     \r\n ");
		sb.append("  				     alert(\"上传保存出错！\");    \r\n ");
		sb.append("  				     return false;     \r\n ");
		sb.append("  				 }     \r\n ");
		sb.append("  				var table=document.getElementById(\"zancunTable\");     \r\n ");
		sb.append("  				table.deleteRow(currZancunFile);     \r\n ");
		sb.append("  			}else{     \r\n ");
		sb.append("  				var myDate = new Date();     \r\n ");
		sb.append("  				var currfileName = currdispayName+\"_\"+username+\"_\"+myDate.getFullYear()+(myDate.getMonth()+1)+myDate.getDate()+myDate.getHours()+myDate.getMinutes()+myDate.getSeconds();       \r\n ");
		sb.append("  				var savefilePath=savePath+\"remote/\"+currfileName+\".pdf\";       \r\n ");
		sb.append("  				var infpath=savePath+\"remote/\"+currfileName+\".inf\";       \r\n ");
		sb.append("          var DJ_IN_CRETIME = myDate.getFullYear()+\"-\"+(myDate.getMonth()+1)+\"-\"+myDate.getDate()+\" \"+myDate.getHours()+\":\"+myDate.getMinutes()+\":\"+myDate.getSeconds();     \r\n ");
		sb.append("          objAIP.AddDocProperty(\"DJ_IN_CRETIME\",DJ_IN_CRETIME);     \r\n ");
		sb.append(" 				  objAIP.ExportEditNodeValue(\"\",infpath,2);     \r\n ");
		sb.append("  				var res = objAIP.SaveTo(savefilePath,\"pdf\",1);     \r\n ");
		sb.append("  				if(res==0){     \r\n ");
		sb.append("  				     alert(\"上传保存出错！\");    \r\n ");
		sb.append("  				     return false;     \r\n ");
		sb.append("  				 }     \r\n ");
		sb.append("  			}     \r\n ");
		sb.append("  			objAIP.CloseDoc(0);     \r\n ");
		sb.append("  		}     \r\n ");
		//加入盖章功能的新版本的暂存和上传方法 结束
		
		
		sb.append(" 	function setbikuan(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.CurrPenWidth = -1; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function setyanse(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.CurrPenColor = -1; \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function setqueren(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.ShowFullScreen = 0;  \r\n");
		sb.append("  			objAIP.SetValue(\"LABEL_ALLNOTES_STATUS\",\"0\");//设置所有节点可选 \r\n ");
		sb.append("    		  objAIP.CurrAction=1; \r\n");
		sb.append(" 				 \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function printdoc(){ \r\n");
		sb.append(" 				var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 				objAIP.PrintDoc(1,1);  \r\n");
//		sb.append(" 				var pagenum = objAIP.PageCount;  \r\n");
//		sb.append(" 				var printret = objAIP.PrintDocEx(\"HP-SJJY-Hotel-Printer\",1,0,1,1,pagenum,1,1,1,0,0);  \r\n");
//		sb.append(" 				if(printret<=0){  \r\n");
//		sb.append(" 					alert(\"打印失败,请将打印机名称设置为：HP-SJJY-Hotel-Printer\"); \r\n");
//		sb.append(" 				} \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		var iszhengfan = \"zheng\"; \r\n");
		sb.append(" 		function zhengjianpaizhao(){ \r\n");
		sb.append(" 			var ret = showModalDialog(\"images/gaopaiyi.htm\",\"\",\"dialogWidth:1000px;dialogHeight:600px;scroll:no;status:no\"); \r\n");
		sb.append(" 			if(ret!=\"success\"){ \r\n");
		sb.append(" 			       return false; \r\n");
		sb.append(" 			} \r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 			var pageCount=objAIP.PageCount; \r\n");
		sb.append(" 			objAIP.Login(\"HWSEALDEMO\", 4, 65535, \"DEMO\", \"\"); \r\n");
		sb.append(" 			if(iszhengfan==\"zheng\"){ \r\n");
		sb.append(" 				objAIP.InsertEmptyPage(pageCount,0,0,0); \r\n");
		sb.append(" 				objAIP.InsertPicture(\"gaopaiyi1\",\"c:/gaopaiyi.jpg\",pageCount,25000,10000,100); \r\n");
		sb.append(" 				iszhengfan=\"fan\"; \r\n");
		sb.append(" 				zhengjianpage = pageCount; \r\n");
		sb.append(" 				objAIP.CurrPage=pageCount; \r\n");
		sb.append("   			    objAIP.DeleteLocalFile(\"C:/gaopaiyi.jpg\");  \r\n");
		sb.append(" 			}else{ \r\n");
		sb.append(" 				objAIP.InsertPicture(\"gaopaiyi2\",\"c:/gaopaiyi.jpg\",zhengjianpage,25000,30000,100); \r\n");
		sb.append("				    iszhengfan=\"zheng\"; \r\n");
		sb.append("				    objAIP.CurrPage=zhengjianpage; \r\n");
		sb.append("   			    objAIP.DeleteLocalFile(\"C:/gaopaiyi.jpg\");  \r\n");
		sb.append(" 			}	 \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		function fujianpaizhao(){ \r\n");
		sb.append(" 			var ret = showModalDialog(\"images/gaopaiyi.htm\",\"\",\"dialogWidth:1000px;dialogHeight:600px;scroll:no;status:no\"); \r\n");
		sb.append(" 			if(ret!=\"success\"){ \r\n");
		sb.append(" 			       return false; \r\n");
		sb.append(" 			} \r\n");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\"); \r\n");
		sb.append(" 			var pageCount=objAIP.PageCount; \r\n");
		sb.append(" 			objAIP.Login(\"HWSEALDEMO\", 4, 65535, \"DEMO\", \"\"); \r\n");
		sb.append(" 			objAIP.InsertEmptyPage(pageCount,0,0,0); \r\n");
		sb.append(" 			objAIP.InsertPicture(\"gaopaifujian\",\"c:/gaopaiyi.jpg\",pageCount,0,0,100); \r\n");
		sb.append(" 			objAIP.CurrPage=pageCount;	 \r\n");
		sb.append("   			objAIP.DeleteLocalFile(\"C:/gaopaiyi.jpg\");  \r\n");
		sb.append(" 		} \r\n");
		sb.append(" 		 function HWPostil1_NotifyFullScreen(){ \r\n");
		sb.append("  					var objAIP=document.getElementById(\"HWPostil1\");  \r\n");
		sb.append("  					if(objAIP.ShowFullScreen == 0){ \r\n");
		sb.append("  						objAIP.CurrAction=1;  \r\n");
		sb.append("  			objAIP.SetValue(\"LABEL_ALLNOTES_STATUS\",\"0\");//设置所有节点可选 \r\n ");
		sb.append("  					  objAIP.JSValue = 0;  \r\n");
		sb.append("  					} \r\n");
		sb.append("  			}  \r\n");
		sb.append(" 		function HWPostil1_NotifyCtrlReady(){\r\n ");
		sb.append(" 			var objAIP=document.getElementById(\"HWPostil1\");\r\n ");
		sb.append(" 			objAIP.JSEnv = 1;						\r\n ");
		sb.append(" 			objAIP.ShowDefMenu = 0 ;						\r\n ");
		sb.append("  			objAIP.ShowScrollBarButton =2;					\r\n ");
		sb.append("  			objAIP.SetPageMode(2,100);	\r\n ");
		sb.append("  			objAIP.SetPageMode(16,1);	\r\n ");
		sb.append("  			objAIP.ShowToolBar = 0;	\r\n ");
		sb.append("  			objAIP.SilentMode = 1;	\r\n ");
		sb.append("  			ocxReady=ocxReady+1;\r\n ");
		sb.append(" 			if(ocxReady==2){				\r\n ");
		sb.append(" 				viewList();\r\n ");
		sb.append(" 			}\r\n ");
		sb.append("    			objAIP.Login(username,2, 65535,\"\",\"\");     \r\n ");
		sb.append(" 		}\r\n ");
		sb.append("		function showZancun(){\r\n");
		sb.append("				if(document.getElementById(\"zancunDiv\").style.display==\"block\"||document.getElementById(\"zancunDiv\").style.display==\"\"){\r\n");
		sb.append("					document.getElementById(\"zancunDiv\").style.display=\"none\";\r\n");
		sb.append("					document.getElementById(\"zancunButton\").src=\"images/004.gif\";\r\n");
		sb.append("				}else{\r\n");
		sb.append("					document.getElementById(\"zancunDiv\").style.display=\"block\";\r\n");
		sb.append("					document.getElementById(\"zancunButton\").src=\"images/003.gif\";\r\n");
		sb.append("				}\r\n");
		sb.append("		}\r\n");
		sb.append("   function HWPostil1_NotifyBeforeAction(lActionType,lType,strName,strValue){  \r\n ");
		sb.append("    			if(lActionType==9){  \r\n ");
		sb.append("    				var objAIP=document.getElementById(\"HWPostil1\"); \r\n ");
		sb.append("    				if(strName==\"Page1.PredefineSignArea\"){ \r\n ");
		sb.append("	    				 var phonearea = objAIP.GetValueEx(\"Page1.PhoneWriteArea\",12,\"\",0,\"\"); \r\n ");
		sb.append("	    				if(phonearea==\"\"){ \r\n ");
		sb.append("	    					objAIP.CurrAction=1;  \r\n ");
		sb.append("	    					objAIP.JSValue = 0; \r\n ");
		sb.append("	    					objAIP.ShowFullScreen = 0; \r\n ");
		sb.append("	    				}else{ \r\n ");
		sb.append("	    					objAIP.CurrAction=1;  \r\n ");
		sb.append("	    					objAIP.JSValue = 0; \r\n ");
		sb.append("	    					objAIP.SetValue(\"Page1.PhoneWriteArea\",\":PROP:ACTIVATE:1\"); \r\n ");
		sb.append("	    				} \r\n ");
		sb.append("	    			}else{ \r\n ");
		sb.append("	    				  objAIP.CurrAction=1;  \r\n ");
		sb.append("	    					objAIP.JSValue = 0; \r\n ");
		sb.append("	    					objAIP.ShowFullScreen = 0; \r\n ");
		sb.append("	    			} \r\n ");
		sb.append("    			}  \r\n ");
		sb.append("    } \r\n ");
		sb.append("    function setxieyi(){ \r\n");
		sb.append("    if(currtemplateName==null||currtemplateName==\"\"){alert(\"请先选择模版！\");return ;} \r\n");
		sb.append("    	if(!isSetXieyi){ \r\n");
		sb.append("    		 	var xieyiStr=document.getElementById(currtemplateName).value; \r\n");
		sb.append("    		 	var xieyiarr=eval(xieyiStr); \r\n");
		sb.append("    		 	var xieyiSelect=document.getElementById(\"xiyiSelect\"); \r\n");
		sb.append("    		 	xieyiSelect.options.length = 0;  \r\n");
		sb.append("    		 	for(var i=0;i<xieyiarr.length;i++){ \r\n");
		sb.append("    		 		var xieyi=xieyiarr[i]; \r\n");
		sb.append("    		 		var opp = new Option(xieyi.xieyiname,xieyi.xieyiid); \r\n");
		sb.append("    		 		opp.id=xieyi.xieyiid+\"Option\"; \r\n");
		sb.append("    		 		xieyiSelect.add(opp); \r\n");
		sb.append("    		 	} \r\n");
		sb.append("    		 	isSetXieyi=true; \r\n");
		sb.append("    	} \r\n");
		sb.append("    	document.getElementById(\"aipDiv\").style.visibility=\"hidden\";//visibility=\"visible\"; \r\n");
		sb.append("    	ShowDialog(\"info\");	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   function ShowDialog(id){	 \r\n");
		sb.append("   var $ = function(id) {return document.getElementById(id);};	 \r\n");
		sb.append("   $(\"overlay\").style.display = 'block';	 \r\n");
		sb.append("   $(id).style.display = 'block';	 \r\n");
		sb.append("   var bb=(document.compatMode && document.compatMode!=\"BackCompat\") ? document.documentElement : document.body;	 \r\n");
		sb.append("   if(document.compatMode && document.compatMode!=\"BackCompat\"){	 \r\n");
		sb.append("   	$(\"overlay\").style.width = bb.scrollWidth+\"px\";	 \r\n");
		sb.append("   	$(\"overlay\").style.height = bb.scrollHeight+\"px\";	 \r\n");
		sb.append("   }else{	 \r\n");
		sb.append("   	$(\"overlay\").style.width = bb.scrollWidth+\"px\";	 \r\n");
		sb.append("   	$(\"overlay\").style.height = bb.scrollHeight+\"px\";	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   $(id).style.left = ((bb.offsetWidth - $(id).offsetWidth)/2)+\"px\";	 \r\n");
		sb.append("   $(id).style.top  = (90 + bb.scrollTop)+\"px\";	 \r\n");
		sb.append("   }	 \r\n");
		sb.append("   function HideDialog(id){	 \r\n");
		sb.append("   	var $ = function(id) {return document.getElementById(id);};	 \r\n");
		sb.append("   	$(\"overlay\").style.display = 'none';	 \r\n");
		sb.append("   	$(id).style.display = 'none';	 \r\n");
		sb.append("   	document.getElementById(\"aipDiv\").style.visibility=\"visible\";	 \r\n");
		sb.append("   	var xieyiSelect=document.getElementById(\"xiyiSelect\");	 \r\n");
		sb.append("   	var objAIP=document.getElementById(\"HWPostil1\"); 	 \r\n");
		sb.append("   	var xuanzhongXieyi=\"\"; 	 \r\n");
		sb.append("   	while(xieyiSelect.selectedIndex>=0){ 	 \r\n");
		sb.append("   		xuanzhongXieyi=xuanzhongXieyi+xieyiSelect.value+\",\"; 	 \r\n");
		sb.append("   		xieyiSelect.remove(xieyiSelect.selectedIndex);   	 \r\n");
		sb.append("   	} 	 \r\n");
		sb.append("   	var xieyis=xuanzhongXieyi.split(\",\"); 	 \r\n");
		sb.append("   	for(var i=0;i<xieyis.length-1;i++){ 	 \r\n");
		sb.append("   		objAIP.MergeFile(objAIP.PageCount,savePath+\"/\"+modelfolder+\"/\"+xieyis[i]); 	 \r\n");
		sb.append("   		objAIP.SetValue(\"companyname\",\"\");	 \r\n");
		sb.append("   		objAIP.SetValue(\"companyname\",\"中国联合网络通信有限公司\"+topcompanyname);	 \r\n");
		sb.append("   		objAIP.SetValue(\"LABEL_ALLNOTES_STATUS\",\"3\"); 	 \r\n");
		sb.append("   	} 	 \r\n");
		sb.append("   } 	 \r\n");
		sb.append(" 	</script>\r\n ");
		sb.append(" 	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=NotifyFullScreen>\r\n ");
		sb.append(" 		 HWPostil1_NotifyFullScreen();\r\n ");
		sb.append(" 	</SCRIPT>\r\n ");
		sb.append(" 	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=NotifyCtrlReady>\r\n ");
		sb.append(" 		 HWPostil1_NotifyCtrlReady();\r\n ");
		sb.append(" 	</SCRIPT>\r\n ");
		sb.append("  	<SCRIPT LANGUAGE=javascript FOR=HWPostil1 EVENT=JSNotifyBeforeAction(lActionType,lType,strName,strValue)> \r\n");
		sb.append("  		 HWPostil1_NotifyBeforeAction(lActionType,lType,strName,strValue); \r\n");
		sb.append("  	</SCRIPT> \r\n");
		return sb.toString();
	}
	
	public static String getBodyStr(List<ModelFileVo> masterplates,List<ModelXieyiVo> modelXieyis){
		StringBuffer sb = new StringBuffer();
		sb.append("<body onload=\"onLoad()\">\r\n");
		sb.append("	<form id=\"business\" method=\"post\">\r\n");
		sb.append("		<input type=\"hidden\" id=\"templateInfo\" name=\"templateInfo\" value=\"").append(getBodyTemplateInfoStr(masterplates)).append("\">\r\n");
		sb.append(getBodyHiddenStr(masterplates,modelXieyis));
		sb.append("	</form>\r\n");
		sb.append("   <div id=\"outerDiv\"> \r\n");
		sb.append("		<div id=\"middleDiv\"> \r\n");
		sb.append("			<div  id=\"zancunDiv\"> \r\n");
		sb.append("				暂存列表<br> \r\n");
		sb.append("				<table id=\"zancunTable\"> \r\n");
		sb.append("				</table> \r\n");
		sb.append("			</div> \r\n");
		sb.append("			<div id=\"banliDiv\"> \r\n");
		sb.append("	 			<div id=\"headerDiv\"> \r\n");
		sb.append("			    	<span style=\"text-align:left\"><image id=\"zancunButton\" src=\"images/003.gif\" onclick=\"showZancun()\" ></span>\r\n");
		sb.append(" 		    	<span><image id=\"TemplateButton\" src=\"images/002.gif\" onclick=\"showTemplateDiv()\"></span>\r\n");
		sb.append(" 				<b><span></span><span id=\"message\">未选择模版</span></b>\r\n");
		sb.append("				</div> \r\n");
		sb.append(" 			<div id=\"TemplateDiv\">\r\n");
		sb.append(" 			</div>\r\n");
		sb.append("		 		<div id=\"mainDiv\"> \r\n");
		sb.append("		 			<div id=\"aipDiv\"> \r\n");
		sb.append("		 				<OBJECT id=HWPostil1 classid=clsid:FF1FE7A0-0578-4FEE-A34E-FB21B277D561 style=\"width:100%;height:100%\"></OBJECT> \r\n");
		
		//加入身份证功能的新版本  读取二代证控件  开始
//		sb.append("	                    <OBJECT id=CardReader_CMCC classid=clsid:D506E603-2C1C-4370-8D26-4563721C2810 style=\"width:0;height:0\"></OBJECT>   \r\n");
		//加入身份证功能的新版本  读取二代证控件  结束
		
		sb.append("		 			</div> \r\n");
		sb.append("		 			<div  id=\"menuBarAIP\" align=\"center\"> \r\n");
		sb.append("		 				<table width=\"100%\" height=\"100%\" border=\"0\"> \r\n");
		sb.append("    				<tr> \r\n");
		sb.append("      				<td align=\"center\" valign=\"middle\"> \r\n");
		sb.append("                         <input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setbikuan\" value=\"协议\" onclick=\"setxieyi()\">  \r\n");
		sb.append("                         <input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setbikuan\" value=\"笔宽\" onclick=\"setbikuan()\">  \r\n");
		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setyanse\" value=\"颜色\" onclick=\"setyanse()\">  \r\n");
		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"qianzi\" value=\"签字\" onclick=\"handWrite()\"> \r\n");
		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"setqueren\" value=\"确认\" onclick=\"setqueren()\">  \r\n");
		
		//加入身份证功能的新版本的添加身份证按钮 开始
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\"  value=\"证件照\" onclick=\"zhengjianpaizhao()\"> \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\"  value=\"附件照\" onclick=\"fujianpaizhao()\"> \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"idcardbutton\" value=\"身份证拍照\" onclick=\"addIdCardImg()\">   \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"idcardbutton\" value=\"身份证识别\" onclick=\"addIdCardInfo()\">   \r\n");
		//加入身份证功能的新版本的添加身份证按钮 结束
		
		sb.append("		 				    &nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"zancun\" value=\"暂存\" onclick=\"saveTemp()\"> \r\n");
		
		//加入盖章功能的新版本的盖个人章和公章按钮 开始
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"privatesealbutton\" value=\"盖个人章\" onclick=\"addPrivateSeal()\">   \r\n");
//		sb.append("      					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"publicsealbutton\" value=\"盖公章\" onclick=\"addPublicSeal()\">   \r\n");
		//加入盖章功能的新版本的盖个人章和公章按钮 结束
		
		sb.append("		 				    &nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"upload\" value=\"上传\" onclick=\"saveUpload()\"> \r\n");
		sb.append("     					&nbsp;&nbsp;<input class='btn1_mouseout' onMouseOver=\"this.className='btn1_mouseover'\" onmouseout=\"this.className='btn1_mouseout'\" onmousedown=\"this.className='btn1_mousedown'\" onmouseup=\"this.className='btn1_mouseup'\" type=\"button\" name=\"printdoc\" value=\"打印\" onclick=\"printdoc()\">  \r\n");
		sb.append("      				</td> \r\n");
		sb.append("    				</tr> \r\n");
		sb.append("  				</table> \r\n");
		sb.append("		 			</div> \r\n");
		sb.append("		 		</div> \r\n");
		sb.append("			</div> \r\n");
		sb.append("		</div> \r\n");
		sb.append("	</div> \r\n");
		sb.append("	<div id=\"overlay\"></div>\r\n");
		sb.append("	<div id=\"info\" class=\"ModalDialog\" style=\"width: 400px;\">\r\n");
		sb.append("		<div class=\"header\">\r\n");
		sb.append("			<span class=\"title\">协议选择</span>\r\n");
		sb.append("		</div>\r\n");
		sb.append("		<div id=\"info_body\" class=\"body\" align=\"center\">\r\n");
		sb.append("			<select id=\"xiyiSelect\" name=\"xiyiSelect\" multiple size=\"6\" style=\"width: 400px;\"></select>\r\n");
		sb.append("		</div>\r\n");
		sb.append("		<div id=\"footer\" class=\"footer\">\r\n");
		sb.append("			<input class=\"BigButton\" onclick=\"HideDialog('info')\" type=\"button\"	value=\"确定\" />\r\n");
		sb.append("		</div>\r\n");
		sb.append("	</div>\r\n");
		sb.append(" </body>\r\n");
		return sb.toString();
	}
	
	public static String getBodyTemplateInfoStr(List<ModelFileVo> masterplates){
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		for(ModelFileVo masterplate : masterplates){
			sb.append("{");
			sb.append("'name':'").append(masterplate.getModel_id()).append("','display':'").append(masterplate.getModel_name()).append("'");
			sb.append("},");
		}
		if(sb.lastIndexOf(",")!=-1){
			sb.deleteCharAt(sb.lastIndexOf(","));
		}
		sb.append("]");
		return sb.toString();
	}
	
	public static String getBodyHiddenStr(List<ModelFileVo> masterplates,List<ModelXieyiVo> modelXieyis){
		StringBuffer sb = new StringBuffer();
		for(ModelFileVo masterplate : masterplates){
			StringBuffer xieyi=new StringBuffer();
			xieyi.append("[");
			for(ModelXieyiVo i:modelXieyis){
				if(i.getModel_id().equals(masterplate.getModel_id())){
					xieyi.append("{'xieyiid':'").append(i.getXieyi_id()).append("','xieyiname':'").append(i.getXieyi_name());
					xieyi.append("'},");
				}
			}
			if(xieyi.lastIndexOf(",")!=-1){
				xieyi.deleteCharAt(xieyi.lastIndexOf(","));
			}
			xieyi.append("]");
			sb.append("<input type=\"hidden\" id=\"").append(masterplate.getModel_id()).append("\" value=\"").append(xieyi.toString()).append("\">\r\n");
		}
		
//		sb.append("<input type=\"hidden\" id=\"身份证图片页\" value=\"").append(ModelData.cardpicturedata).append("\">");
//		sb.append("\r\n");
//		sb.append("<input type=\"hidden\" id=\"身份证信息页\" value=\"").append(ModelData.carddatapagedata).append("\">");
//		sb.append("\r\n");
		return sb.toString();
	}
	
}
